apiVersion: v1
kind: Service
metadata:
  name: {{ include "werft.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "werft.labels" . | nindent 4 }}
spec:
  selector: {{- include "werft.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
