// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AlertScopeApplyConfiguration represents a declarative configuration of the AlertScope type for use
// with apply.
//
// AlertScope narrows what a rule watches. Empty: everything the condition
// applies to (all projects, all nodes, all certificates).
type AlertScopeApplyConfiguration struct {
	// Projects (namespaces) to watch.
	Projects []string `json:"projects,omitempty"`
	// Apps to watch, as "<project>/<app>".
	Apps []string `json:"apps,omitempty"`
}

// AlertScopeApplyConfiguration constructs a declarative configuration of the AlertScope type for use with
// apply.
func AlertScope() *AlertScopeApplyConfiguration {
	return &AlertScopeApplyConfiguration{}
}

// WithProjects adds the given value to the Projects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Projects field.
func (b *AlertScopeApplyConfiguration) WithProjects(values ...string) *AlertScopeApplyConfiguration {
	for i := range values {
		b.Projects = append(b.Projects, values[i])
	}
	return b
}

// WithApps adds the given value to the Apps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Apps field.
func (b *AlertScopeApplyConfiguration) WithApps(values ...string) *AlertScopeApplyConfiguration {
	for i := range values {
		b.Apps = append(b.Apps, values[i])
	}
	return b
}
