// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AlertRuleSpecApplyConfiguration represents a declarative configuration of the AlertRuleSpec type for use
// with apply.
//
// AlertRuleSpec is one alert: a condition, where it applies, how bad it is
// and who hears about it.
type AlertRuleSpecApplyConfiguration struct {
	Condition *apiv1alpha1.AlertCondition `json:"condition,omitempty"`
	// Threshold of the condition: a count (Restarts), percent (MemoryHigh,
	// CPUHigh, VolumeFillingUp, Node*, HTTPErrorRate, DiskWearing) or milliseconds
	// (HTTPLatency). Empty: the condition's default.
	Threshold *int64 `json:"threshold,omitempty"`
	// Window the condition looks at (Restarts, VolumeFillingUp prediction,
	// CertificateExpiring, ScheduleFailing, HTTP*, DiskFailing's media
	// errors). Empty: the default.
	Window *v1.Duration `json:"window,omitempty"`
	// For is how long the condition must hold before the alert fires.
	For *v1.Duration `json:"for,omitempty"`
	// Expr is a MetricsQL expression for Custom rules; each result series is
	// one alert.
	Expr     *string                       `json:"expr,omitempty"`
	Scope    *AlertScopeApplyConfiguration `json:"scope,omitempty"`
	Severity *apiv1alpha1.AlertSeverity    `json:"severity,omitempty"`
	// Channels are NotificationChannel names. Empty: the alert only shows in
	// the console.
	Channels []string `json:"channels,omitempty"`
	// Disabled rules are kept but not evaluated.
	Disabled *bool `json:"disabled,omitempty"`
}

// AlertRuleSpecApplyConfiguration constructs a declarative configuration of the AlertRuleSpec type for use with
// apply.
func AlertRuleSpec() *AlertRuleSpecApplyConfiguration {
	return &AlertRuleSpecApplyConfiguration{}
}

// WithCondition sets the Condition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Condition field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithCondition(value apiv1alpha1.AlertCondition) *AlertRuleSpecApplyConfiguration {
	b.Condition = &value
	return b
}

// WithThreshold sets the Threshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Threshold field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithThreshold(value int64) *AlertRuleSpecApplyConfiguration {
	b.Threshold = &value
	return b
}

// WithWindow sets the Window field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Window field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithWindow(value v1.Duration) *AlertRuleSpecApplyConfiguration {
	b.Window = &value
	return b
}

// WithFor sets the For field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the For field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithFor(value v1.Duration) *AlertRuleSpecApplyConfiguration {
	b.For = &value
	return b
}

// WithExpr sets the Expr field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expr field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithExpr(value string) *AlertRuleSpecApplyConfiguration {
	b.Expr = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithScope(value *AlertScopeApplyConfiguration) *AlertRuleSpecApplyConfiguration {
	b.Scope = value
	return b
}

// WithSeverity sets the Severity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Severity field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithSeverity(value apiv1alpha1.AlertSeverity) *AlertRuleSpecApplyConfiguration {
	b.Severity = &value
	return b
}

// WithChannels adds the given value to the Channels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Channels field.
func (b *AlertRuleSpecApplyConfiguration) WithChannels(values ...string) *AlertRuleSpecApplyConfiguration {
	for i := range values {
		b.Channels = append(b.Channels, values[i])
	}
	return b
}

// WithDisabled sets the Disabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disabled field is set to the value of the last call.
func (b *AlertRuleSpecApplyConfiguration) WithDisabled(value bool) *AlertRuleSpecApplyConfiguration {
	b.Disabled = &value
	return b
}
