// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AlertRuleStatusApplyConfiguration represents a declarative configuration of the AlertRuleStatus type for use
// with apply.
//
// AlertRuleStatus is written by the alerting reconciler.
type AlertRuleStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Expr is the expression Kwerft evaluates for this rule, for reference.
	Expr       *string                          `json:"expr,omitempty"`
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// AlertRuleStatusApplyConfiguration constructs a declarative configuration of the AlertRuleStatus type for use with
// apply.
func AlertRuleStatus() *AlertRuleStatusApplyConfiguration {
	return &AlertRuleStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *AlertRuleStatusApplyConfiguration) WithObservedGeneration(value int64) *AlertRuleStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithExpr sets the Expr field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expr field is set to the value of the last call.
func (b *AlertRuleStatusApplyConfiguration) WithExpr(value string) *AlertRuleStatusApplyConfiguration {
	b.Expr = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *AlertRuleStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *AlertRuleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
