// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AppSourceApplyConfiguration represents a declarative configuration of the AppSource type for use
// with apply.
//
// AppSource says where the container image comes from. Exactly one of Image
// or Git is set.
type AppSourceApplyConfiguration struct {
	Image *ImageSourceApplyConfiguration `json:"image,omitempty"`
	Git   *GitSourceApplyConfiguration   `json:"git,omitempty"`
}

// AppSourceApplyConfiguration constructs a declarative configuration of the AppSource type for use with
// apply.
func AppSource() *AppSourceApplyConfiguration {
	return &AppSourceApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *AppSourceApplyConfiguration) WithImage(value *ImageSourceApplyConfiguration) *AppSourceApplyConfiguration {
	b.Image = value
	return b
}

// WithGit sets the Git field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Git field is set to the value of the last call.
func (b *AppSourceApplyConfiguration) WithGit(value *GitSourceApplyConfiguration) *AppSourceApplyConfiguration {
	b.Git = value
	return b
}
