// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// AppVolumeApplyConfiguration represents a declarative configuration of the AppVolume type for use
// with apply.
//
// AppVolume mounts persistent storage at Path, in one of two forms:
// - Size (and Class): every replica gets its own disk; the App runs as a
// StatefulSet so each replica keeps it.
// - Volume: the shared Volume of that name in the same project, which
// other Apps and Tasks can mount too.
type AppVolumeApplyConfiguration struct {
	Path *string `json:"path,omitempty"`
	// Size of each replica's own disk.
	Size *resource.Quantity `json:"size,omitempty"`
	// Class is local-nvme (fastest, pinned to one node) or hcloud-volume
	// (movable between Hetzner Cloud nodes); empty means local-nvme.
	Class *string `json:"class,omitempty"`
	// Volume names a shared Volume in the same project.
	Volume *string `json:"volume,omitempty"`
	// ReadOnly mounts the storage read-only.
	ReadOnly *bool `json:"readOnly,omitempty"`
}

// AppVolumeApplyConfiguration constructs a declarative configuration of the AppVolume type for use with
// apply.
func AppVolume() *AppVolumeApplyConfiguration {
	return &AppVolumeApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *AppVolumeApplyConfiguration) WithPath(value string) *AppVolumeApplyConfiguration {
	b.Path = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *AppVolumeApplyConfiguration) WithSize(value resource.Quantity) *AppVolumeApplyConfiguration {
	b.Size = &value
	return b
}

// WithClass sets the Class field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Class field is set to the value of the last call.
func (b *AppVolumeApplyConfiguration) WithClass(value string) *AppVolumeApplyConfiguration {
	b.Class = &value
	return b
}

// WithVolume sets the Volume field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Volume field is set to the value of the last call.
func (b *AppVolumeApplyConfiguration) WithVolume(value string) *AppVolumeApplyConfiguration {
	b.Volume = &value
	return b
}

// WithReadOnly sets the ReadOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadOnly field is set to the value of the last call.
func (b *AppVolumeApplyConfiguration) WithReadOnly(value bool) *AppVolumeApplyConfiguration {
	b.ReadOnly = &value
	return b
}
