// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// AvailableUpdateApplyConfiguration represents a declarative configuration of the AvailableUpdate type for use
// with apply.
//
// AvailableUpdate is one release the console could upgrade to.
type AvailableUpdateApplyConfiguration struct {
	Component *apiv1alpha1.UpgradeComponent `json:"component,omitempty"`
	Version   *string                       `json:"version,omitempty"`
	// Kind: Patch or Minor.
	Kind  *string `json:"kind,omitempty"`
	Notes *string `json:"notes,omitempty"`
	// Allowed: preflight-free rules (order, upgradeFrom, supported k3s).
	Allowed *bool   `json:"allowed,omitempty"`
	Reason  *string `json:"reason,omitempty"`
}

// AvailableUpdateApplyConfiguration constructs a declarative configuration of the AvailableUpdate type for use with
// apply.
func AvailableUpdate() *AvailableUpdateApplyConfiguration {
	return &AvailableUpdateApplyConfiguration{}
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *AvailableUpdateApplyConfiguration) WithComponent(value apiv1alpha1.UpgradeComponent) *AvailableUpdateApplyConfiguration {
	b.Component = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AvailableUpdateApplyConfiguration) WithVersion(value string) *AvailableUpdateApplyConfiguration {
	b.Version = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *AvailableUpdateApplyConfiguration) WithKind(value string) *AvailableUpdateApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNotes sets the Notes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Notes field is set to the value of the last call.
func (b *AvailableUpdateApplyConfiguration) WithNotes(value string) *AvailableUpdateApplyConfiguration {
	b.Notes = &value
	return b
}

// WithAllowed sets the Allowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allowed field is set to the value of the last call.
func (b *AvailableUpdateApplyConfiguration) WithAllowed(value bool) *AvailableUpdateApplyConfiguration {
	b.Allowed = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *AvailableUpdateApplyConfiguration) WithReason(value string) *AvailableUpdateApplyConfiguration {
	b.Reason = &value
	return b
}
