// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BackupPlanStatusApplyConfiguration represents a declarative configuration of the BackupPlanStatus type for use
// with apply.
//
// BackupPlanStatus is written by the BackupPlan reconciler.
type BackupPlanStatusApplyConfiguration struct {
	ObservedGeneration *int64                       `json:"observedGeneration,omitempty"`
	LastBackup         *BackupRunApplyConfiguration `json:"lastBackup,omitempty"`
	// LastSuccessfulAt is when the newest Completed backup finished.
	LastSuccessfulAt *v1.Time `json:"lastSuccessfulAt,omitempty"`
	NextRunAt        *v1.Time `json:"nextRunAt,omitempty"`
	// Backups is how many of this plan's backups the bucket holds.
	Backups    *int32                               `json:"backups,omitempty"`
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BackupPlanStatusApplyConfiguration constructs a declarative configuration of the BackupPlanStatus type for use with
// apply.
func BackupPlanStatus() *BackupPlanStatusApplyConfiguration {
	return &BackupPlanStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BackupPlanStatusApplyConfiguration) WithObservedGeneration(value int64) *BackupPlanStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithLastBackup sets the LastBackup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastBackup field is set to the value of the last call.
func (b *BackupPlanStatusApplyConfiguration) WithLastBackup(value *BackupRunApplyConfiguration) *BackupPlanStatusApplyConfiguration {
	b.LastBackup = value
	return b
}

// WithLastSuccessfulAt sets the LastSuccessfulAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulAt field is set to the value of the last call.
func (b *BackupPlanStatusApplyConfiguration) WithLastSuccessfulAt(value v1.Time) *BackupPlanStatusApplyConfiguration {
	b.LastSuccessfulAt = &value
	return b
}

// WithNextRunAt sets the NextRunAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextRunAt field is set to the value of the last call.
func (b *BackupPlanStatusApplyConfiguration) WithNextRunAt(value v1.Time) *BackupPlanStatusApplyConfiguration {
	b.NextRunAt = &value
	return b
}

// WithBackups sets the Backups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backups field is set to the value of the last call.
func (b *BackupPlanStatusApplyConfiguration) WithBackups(value int32) *BackupPlanStatusApplyConfiguration {
	b.Backups = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BackupPlanStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *BackupPlanStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
