// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupsStatusApplyConfiguration represents a declarative configuration of the BackupsStatus type for use
// with apply.
//
// BackupsStatus is the state of the backup target.
type BackupsStatusApplyConfiguration struct {
	// State: NotConfigured, Ready, Error.
	State   *string `json:"state,omitempty"`
	Message *string `json:"message,omitempty"`
	// RecoveryKeyCreatedAt is when the recovery key (the repository
	// password) was made; it was shown once then.
	RecoveryKeyCreatedAt *v1.Time `json:"recoveryKeyCreatedAt,omitempty"`
	LastSuccessfulAt     *v1.Time `json:"lastSuccessfulAt,omitempty"`
	CheckedAt            *v1.Time `json:"checkedAt,omitempty"`
	// EtcdSnapshots: per control-plane node, the last etcd snapshot the
	// node agent uploaded to the bucket (encrypted with the key derived
	// from the recovery key), as the agents report it. Empty while etcd
	// snapshots do not go to the bucket.
	EtcdSnapshots []EtcdSnapshotUploadApplyConfiguration `json:"etcdSnapshots,omitempty"`
}

// BackupsStatusApplyConfiguration constructs a declarative configuration of the BackupsStatus type for use with
// apply.
func BackupsStatus() *BackupsStatusApplyConfiguration {
	return &BackupsStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BackupsStatusApplyConfiguration) WithState(value string) *BackupsStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *BackupsStatusApplyConfiguration) WithMessage(value string) *BackupsStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithRecoveryKeyCreatedAt sets the RecoveryKeyCreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecoveryKeyCreatedAt field is set to the value of the last call.
func (b *BackupsStatusApplyConfiguration) WithRecoveryKeyCreatedAt(value v1.Time) *BackupsStatusApplyConfiguration {
	b.RecoveryKeyCreatedAt = &value
	return b
}

// WithLastSuccessfulAt sets the LastSuccessfulAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulAt field is set to the value of the last call.
func (b *BackupsStatusApplyConfiguration) WithLastSuccessfulAt(value v1.Time) *BackupsStatusApplyConfiguration {
	b.LastSuccessfulAt = &value
	return b
}

// WithCheckedAt sets the CheckedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CheckedAt field is set to the value of the last call.
func (b *BackupsStatusApplyConfiguration) WithCheckedAt(value v1.Time) *BackupsStatusApplyConfiguration {
	b.CheckedAt = &value
	return b
}

// WithEtcdSnapshots adds the given value to the EtcdSnapshots field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EtcdSnapshots field.
func (b *BackupsStatusApplyConfiguration) WithEtcdSnapshots(values ...*EtcdSnapshotUploadApplyConfiguration) *BackupsStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEtcdSnapshots")
		}
		b.EtcdSnapshots = append(b.EtcdSnapshots, *values[i])
	}
	return b
}
