// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupRunApplyConfiguration represents a declarative configuration of the BackupRun type for use
// with apply.
//
// BackupRun is one backup of a plan.
type BackupRunApplyConfiguration struct {
	// Name of the Velero Backup.
	Name *string `json:"name,omitempty"`
	// Phase: InProgress, Completed, PartiallyFailed, Failed.
	Phase       *string  `json:"phase,omitempty"`
	StartedAt   *v1.Time `json:"startedAt,omitempty"`
	CompletedAt *v1.Time `json:"completedAt,omitempty"`
	ExpiresAt   *v1.Time `json:"expiresAt,omitempty"`
	Items       *int32   `json:"items,omitempty"`
	Warnings    *int32   `json:"warnings,omitempty"`
	Errors      *int32   `json:"errors,omitempty"`
	Message     *string  `json:"message,omitempty"`
}

// BackupRunApplyConfiguration constructs a declarative configuration of the BackupRun type for use with
// apply.
func BackupRun() *BackupRunApplyConfiguration {
	return &BackupRunApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithName(value string) *BackupRunApplyConfiguration {
	b.Name = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithPhase(value string) *BackupRunApplyConfiguration {
	b.Phase = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithStartedAt(value v1.Time) *BackupRunApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithCompletedAt(value v1.Time) *BackupRunApplyConfiguration {
	b.CompletedAt = &value
	return b
}

// WithExpiresAt sets the ExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiresAt field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithExpiresAt(value v1.Time) *BackupRunApplyConfiguration {
	b.ExpiresAt = &value
	return b
}

// WithItems sets the Items field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Items field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithItems(value int32) *BackupRunApplyConfiguration {
	b.Items = &value
	return b
}

// WithWarnings sets the Warnings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Warnings field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithWarnings(value int32) *BackupRunApplyConfiguration {
	b.Warnings = &value
	return b
}

// WithErrors sets the Errors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Errors field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithErrors(value int32) *BackupRunApplyConfiguration {
	b.Errors = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *BackupRunApplyConfiguration) WithMessage(value string) *BackupRunApplyConfiguration {
	b.Message = &value
	return b
}
