// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BackupSettingsApplyConfiguration represents a declarative configuration of the BackupSettings type for use
// with apply.
//
// BackupSettings: the S3-compatible bucket backups go to (Hetzner Object
// Storage) and the etcd snapshot schedule.
type BackupSettingsApplyConfiguration struct {
	// Endpoint, e.g. https://fsn1.your-objectstorage.com.
	Endpoint *string `json:"endpoint,omitempty"`
	// Region, e.g. fsn1.
	Region *string `json:"region,omitempty"`
	Bucket *string `json:"bucket,omitempty"`
	// Prefix inside the bucket, so several consoles can share one
	// (default: the console's hostname).
	Prefix *string `json:"prefix,omitempty"`
	// EtcdSnapshots: k3s's own snapshots of the cluster state, kept locally
	// and copied to the same bucket (folder <prefix>/etcd); nil means every
	// 6 hours, 28 kept. The installer applies a changed schedule on its next
	// run (k3s reads it only when it starts).
	EtcdSnapshots *EtcdSnapshotSettingsApplyConfiguration `json:"etcdSnapshots,omitempty"`
}

// BackupSettingsApplyConfiguration constructs a declarative configuration of the BackupSettings type for use with
// apply.
func BackupSettings() *BackupSettingsApplyConfiguration {
	return &BackupSettingsApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *BackupSettingsApplyConfiguration) WithEndpoint(value string) *BackupSettingsApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BackupSettingsApplyConfiguration) WithRegion(value string) *BackupSettingsApplyConfiguration {
	b.Region = &value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *BackupSettingsApplyConfiguration) WithBucket(value string) *BackupSettingsApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *BackupSettingsApplyConfiguration) WithPrefix(value string) *BackupSettingsApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithEtcdSnapshots sets the EtcdSnapshots field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EtcdSnapshots field is set to the value of the last call.
func (b *BackupSettingsApplyConfiguration) WithEtcdSnapshots(value *EtcdSnapshotSettingsApplyConfiguration) *BackupSettingsApplyConfiguration {
	b.EtcdSnapshots = value
	return b
}
