// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupPlanSpecApplyConfiguration represents a declarative configuration of the BackupPlanSpec type for use
// with apply.
//
// BackupPlanSpec schedules backups.
type BackupPlanSpecApplyConfiguration struct {
	Scope *apiv1alpha1.BackupScope `json:"scope,omitempty"`
	// Projects of a Projects plan.
	Projects []string `json:"projects,omitempty"`
	// Schedule in cron syntax, in UTC.
	Schedule *string `json:"schedule,omitempty"`
	// Retention: how long each backup is kept (default 14 days).
	Retention *v1.Duration `json:"retention,omitempty"`
	// Volumes includes the data of the projects' Volumes and of App and
	// Task disks (file level). Off backs up the objects only.
	Volumes *bool `json:"volumes,omitempty"`
	// Paused stops scheduled runs; "Back up now" still works.
	Paused *bool `json:"paused,omitempty"`
}

// BackupPlanSpecApplyConfiguration constructs a declarative configuration of the BackupPlanSpec type for use with
// apply.
func BackupPlanSpec() *BackupPlanSpecApplyConfiguration {
	return &BackupPlanSpecApplyConfiguration{}
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *BackupPlanSpecApplyConfiguration) WithScope(value apiv1alpha1.BackupScope) *BackupPlanSpecApplyConfiguration {
	b.Scope = &value
	return b
}

// WithProjects adds the given value to the Projects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Projects field.
func (b *BackupPlanSpecApplyConfiguration) WithProjects(values ...string) *BackupPlanSpecApplyConfiguration {
	for i := range values {
		b.Projects = append(b.Projects, values[i])
	}
	return b
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *BackupPlanSpecApplyConfiguration) WithSchedule(value string) *BackupPlanSpecApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithRetention sets the Retention field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retention field is set to the value of the last call.
func (b *BackupPlanSpecApplyConfiguration) WithRetention(value v1.Duration) *BackupPlanSpecApplyConfiguration {
	b.Retention = &value
	return b
}

// WithVolumes sets the Volumes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Volumes field is set to the value of the last call.
func (b *BackupPlanSpecApplyConfiguration) WithVolumes(value bool) *BackupPlanSpecApplyConfiguration {
	b.Volumes = &value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *BackupPlanSpecApplyConfiguration) WithPaused(value bool) *BackupPlanSpecApplyConfiguration {
	b.Paused = &value
	return b
}
