// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CertificateStateApplyConfiguration represents a declarative configuration of the CertificateState type for use
// with apply.
//
// CertificateState is one certificate the console itself depends on.
type CertificateStateApplyConfiguration struct {
	// Name of the cert-manager Certificate in kwerft-system.
	Name *string `json:"name,omitempty"`
	// Hostnames the certificate covers.
	Hostnames []string `json:"hostnames,omitempty"`
	// Purpose: console, console-next, console-previous or apps-wildcard.
	Purpose *string `json:"purpose,omitempty"`
	// Ready mirrors the Certificate's Ready condition.
	Ready    *bool    `json:"ready,omitempty"`
	Reason   *string  `json:"reason,omitempty"`
	Message  *string  `json:"message,omitempty"`
	NotAfter *v1.Time `json:"notAfter,omitempty"`
}

// CertificateStateApplyConfiguration constructs a declarative configuration of the CertificateState type for use with
// apply.
func CertificateState() *CertificateStateApplyConfiguration {
	return &CertificateStateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CertificateStateApplyConfiguration) WithName(value string) *CertificateStateApplyConfiguration {
	b.Name = &value
	return b
}

// WithHostnames adds the given value to the Hostnames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Hostnames field.
func (b *CertificateStateApplyConfiguration) WithHostnames(values ...string) *CertificateStateApplyConfiguration {
	for i := range values {
		b.Hostnames = append(b.Hostnames, values[i])
	}
	return b
}

// WithPurpose sets the Purpose field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Purpose field is set to the value of the last call.
func (b *CertificateStateApplyConfiguration) WithPurpose(value string) *CertificateStateApplyConfiguration {
	b.Purpose = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *CertificateStateApplyConfiguration) WithReady(value bool) *CertificateStateApplyConfiguration {
	b.Ready = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *CertificateStateApplyConfiguration) WithReason(value string) *CertificateStateApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *CertificateStateApplyConfiguration) WithMessage(value string) *CertificateStateApplyConfiguration {
	b.Message = &value
	return b
}

// WithNotAfter sets the NotAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotAfter field is set to the value of the last call.
func (b *CertificateStateApplyConfiguration) WithNotAfter(value v1.Time) *CertificateStateApplyConfiguration {
	b.NotAfter = &value
	return b
}
