// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CloudServerStatusApplyConfiguration represents a declarative configuration of the CloudServerStatus type for use
// with apply.
//
// CloudServerStatus is one node that is a Hetzner Cloud server.
type CloudServerStatusApplyConfiguration struct {
	Node     *string `json:"node,omitempty"`
	ID       *int64  `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Location *string `json:"location,omitempty"`
	// Labelled: the server carries kwerft.dev/cluster=<this cluster> (Kwerft
	// created it); others (the installer's first server) are named one by
	// one in the firewall and the Load Balancer.
	Labelled *bool `json:"labelled,omitempty"`
}

// CloudServerStatusApplyConfiguration constructs a declarative configuration of the CloudServerStatus type for use with
// apply.
func CloudServerStatus() *CloudServerStatusApplyConfiguration {
	return &CloudServerStatusApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *CloudServerStatusApplyConfiguration) WithNode(value string) *CloudServerStatusApplyConfiguration {
	b.Node = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *CloudServerStatusApplyConfiguration) WithID(value int64) *CloudServerStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CloudServerStatusApplyConfiguration) WithName(value string) *CloudServerStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *CloudServerStatusApplyConfiguration) WithLocation(value string) *CloudServerStatusApplyConfiguration {
	b.Location = &value
	return b
}

// WithLabelled sets the Labelled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Labelled field is set to the value of the last call.
func (b *CloudServerStatusApplyConfiguration) WithLabelled(value bool) *CloudServerStatusApplyConfiguration {
	b.Labelled = &value
	return b
}
