// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterHostnameApplyConfiguration represents a declarative configuration of the ClusterHostname type for use
// with apply.
//
// ClusterHostname is a public hostname one of a remote cluster's Domains
// holds.
type ClusterHostnameApplyConfiguration struct {
	Hostname *string `json:"hostname,omitempty"`
	// Project (namespace) of the Domain.
	Project *string `json:"project,omitempty"`
	// Since is when the Domain was created: of two clusters wanting a
	// hostname, the older claim gets the record.
	Since *v1.Time `json:"since,omitempty"`
}

// ClusterHostnameApplyConfiguration constructs a declarative configuration of the ClusterHostname type for use with
// apply.
func ClusterHostname() *ClusterHostnameApplyConfiguration {
	return &ClusterHostnameApplyConfiguration{}
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *ClusterHostnameApplyConfiguration) WithHostname(value string) *ClusterHostnameApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithProject sets the Project field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Project field is set to the value of the last call.
func (b *ClusterHostnameApplyConfiguration) WithProject(value string) *ClusterHostnameApplyConfiguration {
	b.Project = &value
	return b
}

// WithSince sets the Since field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Since field is set to the value of the last call.
func (b *ClusterHostnameApplyConfiguration) WithSince(value v1.Time) *ClusterHostnameApplyConfiguration {
	b.Since = &value
	return b
}
