// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// ClusterSpecApplyConfiguration represents a declarative configuration of the ClusterSpec type for use
// with apply.
//
// ClusterSpec is one Kubernetes cluster the console manages.
type ClusterSpecApplyConfiguration struct {
	DisplayName  *string                               `json:"displayName,omitempty"`
	Provider     *apiv1alpha1.ClusterProvider          `json:"provider,omitempty"`
	HetznerCloud *HetznerClusterSpecApplyConfiguration `json:"hetznerCloud,omitempty"`
	// ConsoleDomain the cluster's own ingress serves apps under is set in
	// that cluster (ConsoleSettings there); this cluster's apps domain, if
	// different, is shown for reference.
	AppsDomain *string `json:"appsDomain,omitempty"`
}

// ClusterSpecApplyConfiguration constructs a declarative configuration of the ClusterSpec type for use with
// apply.
func ClusterSpec() *ClusterSpecApplyConfiguration {
	return &ClusterSpecApplyConfiguration{}
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithDisplayName(value string) *ClusterSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithProvider(value apiv1alpha1.ClusterProvider) *ClusterSpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithHetznerCloud sets the HetznerCloud field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HetznerCloud field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithHetznerCloud(value *HetznerClusterSpecApplyConfiguration) *ClusterSpecApplyConfiguration {
	b.HetznerCloud = value
	return b
}

// WithAppsDomain sets the AppsDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppsDomain field is set to the value of the last call.
func (b *ClusterSpecApplyConfiguration) WithAppsDomain(value string) *ClusterSpecApplyConfiguration {
	b.AppsDomain = &value
	return b
}
