// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterStatusApplyConfiguration represents a declarative configuration of the ClusterStatus type for use
// with apply.
//
// ClusterStatus is written by the cluster reconciler and the agent tunnel.
type ClusterStatusApplyConfiguration struct {
	ObservedGeneration *int64                    `json:"observedGeneration,omitempty"`
	Phase              *apiv1alpha1.ClusterPhase `json:"phase,omitempty"`
	// LastSeen is when the agent last answered.
	LastSeen          *v1.Time `json:"lastSeen,omitempty"`
	AgentVersion      *string  `json:"agentVersion,omitempty"`
	KubernetesVersion *string  `json:"kubernetesVersion,omitempty"`
	Nodes             *int32   `json:"nodes,omitempty"`
	ReadyNodes        *int32   `json:"readyNodes,omitempty"`
	// HetznerCloud is what the cluster's own Hetzner Cloud reconciler last
	// reported (its Cloud Firewall and Load Balancer); hetzner-cloud
	// clusters only, copied through the agent's tunnel.
	HetznerCloud *HetznerCloudStatusApplyConfiguration `json:"hetznerCloud,omitempty"`
	Conditions   []metav1.ConditionApplyConfiguration  `json:"conditions,omitempty"`
}

// ClusterStatusApplyConfiguration constructs a declarative configuration of the ClusterStatus type for use with
// apply.
func ClusterStatus() *ClusterStatusApplyConfiguration {
	return &ClusterStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithObservedGeneration(value int64) *ClusterStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithPhase(value apiv1alpha1.ClusterPhase) *ClusterStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithLastSeen sets the LastSeen field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSeen field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithLastSeen(value v1.Time) *ClusterStatusApplyConfiguration {
	b.LastSeen = &value
	return b
}

// WithAgentVersion sets the AgentVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentVersion field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithAgentVersion(value string) *ClusterStatusApplyConfiguration {
	b.AgentVersion = &value
	return b
}

// WithKubernetesVersion sets the KubernetesVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubernetesVersion field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithKubernetesVersion(value string) *ClusterStatusApplyConfiguration {
	b.KubernetesVersion = &value
	return b
}

// WithNodes sets the Nodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Nodes field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithNodes(value int32) *ClusterStatusApplyConfiguration {
	b.Nodes = &value
	return b
}

// WithReadyNodes sets the ReadyNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyNodes field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithReadyNodes(value int32) *ClusterStatusApplyConfiguration {
	b.ReadyNodes = &value
	return b
}

// WithHetznerCloud sets the HetznerCloud field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HetznerCloud field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithHetznerCloud(value *HetznerCloudStatusApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.HetznerCloud = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
