// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ConsoleSettingsStatusApplyConfiguration represents a declarative configuration of the ConsoleSettingsStatus type for use
// with apply.
//
// ConsoleSettingsStatus is written by the Domain reconciler, which owns the
// shared Gateway.
type ConsoleSettingsStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// ConsoleDomain is the hostname the console is served on now. While a
	// change waits for its certificate it still names the old hostname.
	ConsoleDomain *string `json:"consoleDomain,omitempty"`
	// PreviousConsoleDomain redirects to ConsoleDomain for a day after a
	// switch, so open tabs and bookmarks find the new name.
	PreviousConsoleDomain *string  `json:"previousConsoleDomain,omitempty"`
	SwitchedAt            *v1.Time `json:"switchedAt,omitempty"`
	// WildcardDomain is "*.<appsDomain>" once the wildcard listener serves
	// apps (its certificate is issued); empty otherwise.
	WildcardDomain *string `json:"wildcardDomain,omitempty"`
	// PublicAddresses are the nodes' external IPs: where DNS records for the
	// console and apps must point.
	PublicAddresses []string `json:"publicAddresses,omitempty"`
	// Certificates the console and the wildcard listener use.
	Certificates []CertificateStateApplyConfiguration `json:"certificates,omitempty"`
	// DNS is what the DNS reconciler did with spec.dns.manageRecords. It has
	// a field of its own because another reconciler writes the rest of the
	// status.
	DNS        *DNSStatusApplyConfiguration         `json:"dns,omitempty"`
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ConsoleSettingsStatusApplyConfiguration constructs a declarative configuration of the ConsoleSettingsStatus type for use with
// apply.
func ConsoleSettingsStatus() *ConsoleSettingsStatusApplyConfiguration {
	return &ConsoleSettingsStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ConsoleSettingsStatusApplyConfiguration) WithObservedGeneration(value int64) *ConsoleSettingsStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConsoleDomain sets the ConsoleDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsoleDomain field is set to the value of the last call.
func (b *ConsoleSettingsStatusApplyConfiguration) WithConsoleDomain(value string) *ConsoleSettingsStatusApplyConfiguration {
	b.ConsoleDomain = &value
	return b
}

// WithPreviousConsoleDomain sets the PreviousConsoleDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PreviousConsoleDomain field is set to the value of the last call.
func (b *ConsoleSettingsStatusApplyConfiguration) WithPreviousConsoleDomain(value string) *ConsoleSettingsStatusApplyConfiguration {
	b.PreviousConsoleDomain = &value
	return b
}

// WithSwitchedAt sets the SwitchedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchedAt field is set to the value of the last call.
func (b *ConsoleSettingsStatusApplyConfiguration) WithSwitchedAt(value v1.Time) *ConsoleSettingsStatusApplyConfiguration {
	b.SwitchedAt = &value
	return b
}

// WithWildcardDomain sets the WildcardDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WildcardDomain field is set to the value of the last call.
func (b *ConsoleSettingsStatusApplyConfiguration) WithWildcardDomain(value string) *ConsoleSettingsStatusApplyConfiguration {
	b.WildcardDomain = &value
	return b
}

// WithPublicAddresses adds the given value to the PublicAddresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PublicAddresses field.
func (b *ConsoleSettingsStatusApplyConfiguration) WithPublicAddresses(values ...string) *ConsoleSettingsStatusApplyConfiguration {
	for i := range values {
		b.PublicAddresses = append(b.PublicAddresses, values[i])
	}
	return b
}

// WithCertificates adds the given value to the Certificates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Certificates field.
func (b *ConsoleSettingsStatusApplyConfiguration) WithCertificates(values ...*CertificateStateApplyConfiguration) *ConsoleSettingsStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCertificates")
		}
		b.Certificates = append(b.Certificates, *values[i])
	}
	return b
}

// WithDNS sets the DNS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNS field is set to the value of the last call.
func (b *ConsoleSettingsStatusApplyConfiguration) WithDNS(value *DNSStatusApplyConfiguration) *ConsoleSettingsStatusApplyConfiguration {
	b.DNS = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ConsoleSettingsStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ConsoleSettingsStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
