// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// ConsoleSettingsSpecApplyConfiguration represents a declarative configuration of the ConsoleSettingsSpec type for use
// with apply.
//
// ConsoleSettingsSpec is what owners and admins choose on the Settings page
// (or the installer from --domain and --config).
type ConsoleSettingsSpecApplyConfiguration struct {
	// ConsoleDomain is the console's hostname. Empty falls back to the
	// --console-domain flag the installer passed. Changing it adds a listener
	// for the new name; the console moves there once its certificate is
	// issued (status.consoleDomain).
	ConsoleDomain *string `json:"consoleDomain,omitempty"`
	// AppsDomain is the base domain for apps, e.g. apps.example.com. The
	// deploy wizard suggests <app>.<appsDomain>. With tls dns01, hostnames
	// one label below it share a wildcard listener and certificate.
	AppsDomain *string `json:"appsDomain,omitempty"`
	// TLS is how app certificates are issued.
	TLS *apiv1alpha1.TLSMode `json:"tls,omitempty"`
	// DNS is the provider for tls dns01 and for managed records. Its API
	// token lives in the Secret kwerft-dns-token (key "token") in
	// kwerft-system, which owners and admins may write through the console
	// but nobody reads back.
	DNS *DNSSettingsApplyConfiguration `json:"dns,omitempty"`
}

// ConsoleSettingsSpecApplyConfiguration constructs a declarative configuration of the ConsoleSettingsSpec type for use with
// apply.
func ConsoleSettingsSpec() *ConsoleSettingsSpecApplyConfiguration {
	return &ConsoleSettingsSpecApplyConfiguration{}
}

// WithConsoleDomain sets the ConsoleDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsoleDomain field is set to the value of the last call.
func (b *ConsoleSettingsSpecApplyConfiguration) WithConsoleDomain(value string) *ConsoleSettingsSpecApplyConfiguration {
	b.ConsoleDomain = &value
	return b
}

// WithAppsDomain sets the AppsDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppsDomain field is set to the value of the last call.
func (b *ConsoleSettingsSpecApplyConfiguration) WithAppsDomain(value string) *ConsoleSettingsSpecApplyConfiguration {
	b.AppsDomain = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *ConsoleSettingsSpecApplyConfiguration) WithTLS(value apiv1alpha1.TLSMode) *ConsoleSettingsSpecApplyConfiguration {
	b.TLS = &value
	return b
}

// WithDNS sets the DNS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNS field is set to the value of the last call.
func (b *ConsoleSettingsSpecApplyConfiguration) WithDNS(value *DNSSettingsApplyConfiguration) *ConsoleSettingsSpecApplyConfiguration {
	b.DNS = value
	return b
}
