// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DerivedSecretKeyApplyConfiguration represents a declarative configuration of the DerivedSecretKey type for use
// with apply.
//
// DerivedSecretKey is a value built from a template with ${KEY} references
// to the set's other keys, e.g.
// postgres://app:${PASSWORD}@postgres-main:5432/app.
type DerivedSecretKeyApplyConfiguration struct {
	Key      *string `json:"key,omitempty"`
	Template *string `json:"template,omitempty"`
}

// DerivedSecretKeyApplyConfiguration constructs a declarative configuration of the DerivedSecretKey type for use with
// apply.
func DerivedSecretKey() *DerivedSecretKeyApplyConfiguration {
	return &DerivedSecretKeyApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *DerivedSecretKeyApplyConfiguration) WithKey(value string) *DerivedSecretKeyApplyConfiguration {
	b.Key = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *DerivedSecretKeyApplyConfiguration) WithTemplate(value string) *DerivedSecretKeyApplyConfiguration {
	b.Template = &value
	return b
}
