// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// DNSRecordStatusApplyConfiguration represents a declarative configuration of the DNSRecordStatus type for use
// with apply.
//
// DNSRecordStatus is one hostname Kwerft keeps records for.
type DNSRecordStatusApplyConfiguration struct {
	// Hostname, e.g. ops.example.com or *.apps.example.com.
	Hostname *string `json:"hostname,omitempty"`
	// Purpose: console, console-next, console-previous or apps.
	Purpose *string `json:"purpose,omitempty"`
	// Zone that contains the hostname; empty for NoZone.
	Zone *string `json:"zone,omitempty"`
	// State of the hostname's records.
	State *apiv1alpha1.DNSRecordState `json:"state,omitempty"`
	// Values the hostname's A and AAAA records hold now.
	Values  []string `json:"values,omitempty"`
	Message *string  `json:"message,omitempty"`
}

// DNSRecordStatusApplyConfiguration constructs a declarative configuration of the DNSRecordStatus type for use with
// apply.
func DNSRecordStatus() *DNSRecordStatusApplyConfiguration {
	return &DNSRecordStatusApplyConfiguration{}
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithHostname(value string) *DNSRecordStatusApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithPurpose sets the Purpose field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Purpose field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithPurpose(value string) *DNSRecordStatusApplyConfiguration {
	b.Purpose = &value
	return b
}

// WithZone sets the Zone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Zone field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithZone(value string) *DNSRecordStatusApplyConfiguration {
	b.Zone = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithState(value apiv1alpha1.DNSRecordState) *DNSRecordStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithValues adds the given value to the Values field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Values field.
func (b *DNSRecordStatusApplyConfiguration) WithValues(values ...string) *DNSRecordStatusApplyConfiguration {
	for i := range values {
		b.Values = append(b.Values, values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DNSRecordStatusApplyConfiguration) WithMessage(value string) *DNSRecordStatusApplyConfiguration {
	b.Message = &value
	return b
}
