// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DNSStatusApplyConfiguration represents a declarative configuration of the DNSStatus type for use
// with apply.
//
// DNSStatus is the outcome of the last sync with the DNS provider.
type DNSStatusApplyConfiguration struct {
	// Records Kwerft keeps, one entry per hostname.
	Records []DNSRecordStatusApplyConfiguration `json:"records,omitempty"`
	// Zones are the primary zones in the token's project: hostnames in them
	// get their records from Kwerft, so the console need not wait for DNS
	// before using them.
	Zones []string `json:"zones,omitempty"`
	// Message explains a problem that kept the whole sync from running (no
	// token, token rejected, no public address); empty when it ran.
	Message *string `json:"message,omitempty"`
	// SyncedAt is when the provider was last read.
	SyncedAt *v1.Time `json:"syncedAt,omitempty"`
}

// DNSStatusApplyConfiguration constructs a declarative configuration of the DNSStatus type for use with
// apply.
func DNSStatus() *DNSStatusApplyConfiguration {
	return &DNSStatusApplyConfiguration{}
}

// WithRecords adds the given value to the Records field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Records field.
func (b *DNSStatusApplyConfiguration) WithRecords(values ...*DNSRecordStatusApplyConfiguration) *DNSStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRecords")
		}
		b.Records = append(b.Records, *values[i])
	}
	return b
}

// WithZones adds the given value to the Zones field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Zones field.
func (b *DNSStatusApplyConfiguration) WithZones(values ...string) *DNSStatusApplyConfiguration {
	for i := range values {
		b.Zones = append(b.Zones, values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DNSStatusApplyConfiguration) WithMessage(value string) *DNSStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithSyncedAt sets the SyncedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SyncedAt field is set to the value of the last call.
func (b *DNSStatusApplyConfiguration) WithSyncedAt(value v1.Time) *DNSStatusApplyConfiguration {
	b.SyncedAt = &value
	return b
}
