// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DNSSettingsApplyConfiguration represents a declarative configuration of the DNSSettings type for use
// with apply.
//
// DNSSettings is the DNS provider that hosts the zones of the console
// hostname and the apps domain.
type DNSSettingsApplyConfiguration struct {
	// Provider of the zones. Only Hetzner (DNS in the Hetzner Console, Cloud
	// API) for now. It solves DNS-01 challenges for tls dns01.
	Provider *string `json:"provider,omitempty"`
	// ManageRecords makes Kwerft keep A and AAAA records for the console
	// hostname and *.<appsDomain> pointing at the nodes' public addresses
	// (status.publicAddresses). It labels the records it creates and never
	// changes records it did not create. Turning it off leaves the records
	// in place.
	ManageRecords *bool `json:"manageRecords,omitempty"`
}

// DNSSettingsApplyConfiguration constructs a declarative configuration of the DNSSettings type for use with
// apply.
func DNSSettings() *DNSSettingsApplyConfiguration {
	return &DNSSettingsApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *DNSSettingsApplyConfiguration) WithProvider(value string) *DNSSettingsApplyConfiguration {
	b.Provider = &value
	return b
}

// WithManageRecords sets the ManageRecords field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManageRecords field is set to the value of the last call.
func (b *DNSSettingsApplyConfiguration) WithManageRecords(value bool) *DNSSettingsApplyConfiguration {
	b.ManageRecords = &value
	return b
}
