// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DomainSpecApplyConfiguration represents a declarative configuration of the DomainSpec type for use
// with apply.
//
// DomainSpec is a public hostname served over HTTPS through the shared
// Gateway. Apps create a Domain for each public port automatically; the
// Domain reconciler gives it a Gateway listener and a certificate.
type DomainSpecApplyConfiguration struct {
	// Hostname, lowercase, e.g. api.example.com. Fixed once created: a
	// Domain's claim and listener belong to one hostname. Hostnames one label
	// below the apps domain share the wildcard listener when it has DNS-01.
	Hostname *string `json:"hostname,omitempty"`
}

// DomainSpecApplyConfiguration constructs a declarative configuration of the DomainSpec type for use with
// apply.
func DomainSpec() *DomainSpecApplyConfiguration {
	return &DomainSpecApplyConfiguration{}
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *DomainSpecApplyConfiguration) WithHostname(value string) *DomainSpecApplyConfiguration {
	b.Hostname = &value
	return b
}
