// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DomainStatusApplyConfiguration represents a declarative configuration of the DomainStatus type for use
// with apply.
//
// DomainStatus is written by the Domain reconciler.
type DomainStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Listener is the Gateway listener serving this hostname over HTTPS.
	// HTTPRoutes attach to it with sectionName.
	Listener *string `json:"listener,omitempty"`
	// NotAfter is when the current certificate expires.
	NotAfter   *v1.Time                             `json:"notAfter,omitempty"`
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// DomainStatusApplyConfiguration constructs a declarative configuration of the DomainStatus type for use with
// apply.
func DomainStatus() *DomainStatusApplyConfiguration {
	return &DomainStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DomainStatusApplyConfiguration) WithObservedGeneration(value int64) *DomainStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithListener sets the Listener field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Listener field is set to the value of the last call.
func (b *DomainStatusApplyConfiguration) WithListener(value string) *DomainStatusApplyConfiguration {
	b.Listener = &value
	return b
}

// WithNotAfter sets the NotAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotAfter field is set to the value of the last call.
func (b *DomainStatusApplyConfiguration) WithNotAfter(value v1.Time) *DomainStatusApplyConfiguration {
	b.NotAfter = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DomainStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *DomainStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
