// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// EmailSettingsApplyConfiguration represents a declarative configuration of the EmailSettings type for use
// with apply.
//
// EmailSettings: SMTP. The password is secret (key "password").
type EmailSettingsApplyConfiguration struct {
	To   []string `json:"to,omitempty"`
	From *string  `json:"from,omitempty"`
	// SMTPHost is host:port, e.g. smtp.example.com:587 (STARTTLS required).
	SMTPHost *string `json:"smtpHost,omitempty"`
	Username *string `json:"username,omitempty"`
}

// EmailSettingsApplyConfiguration constructs a declarative configuration of the EmailSettings type for use with
// apply.
func EmailSettings() *EmailSettingsApplyConfiguration {
	return &EmailSettingsApplyConfiguration{}
}

// WithTo adds the given value to the To field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the To field.
func (b *EmailSettingsApplyConfiguration) WithTo(values ...string) *EmailSettingsApplyConfiguration {
	for i := range values {
		b.To = append(b.To, values[i])
	}
	return b
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *EmailSettingsApplyConfiguration) WithFrom(value string) *EmailSettingsApplyConfiguration {
	b.From = &value
	return b
}

// WithSMTPHost sets the SMTPHost field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SMTPHost field is set to the value of the last call.
func (b *EmailSettingsApplyConfiguration) WithSMTPHost(value string) *EmailSettingsApplyConfiguration {
	b.SMTPHost = &value
	return b
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *EmailSettingsApplyConfiguration) WithUsername(value string) *EmailSettingsApplyConfiguration {
	b.Username = &value
	return b
}
