// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EtcdSnapshotUploadApplyConfiguration represents a declarative configuration of the EtcdSnapshotUpload type for use
// with apply.
//
// EtcdSnapshotUpload is one node's etcd snapshot uploads.
type EtcdSnapshotUploadApplyConfiguration struct {
	// Node is the control-plane node whose local snapshots these are
	// (folder <prefix>/etcd/<node> in the bucket).
	Node *string `json:"node,omitempty"`
	// Name of the newest snapshot in the bucket, e.g.
	// etcd-snapshot-server-1-1759665600.zip.
	Name *string `json:"name,omitempty"`
	// UploadedAt is when the agent last finished an upload.
	UploadedAt *v1.Time `json:"uploadedAt,omitempty"`
	// CheckedAt is when the agent last compared its snapshots with the
	// bucket.
	CheckedAt *v1.Time `json:"checkedAt,omitempty"`
	// Stored is how many of this node's snapshots the bucket holds.
	Stored *int32 `json:"stored,omitempty"`
	// Message says what went wrong; empty when the last pass succeeded.
	Message *string `json:"message,omitempty"`
}

// EtcdSnapshotUploadApplyConfiguration constructs a declarative configuration of the EtcdSnapshotUpload type for use with
// apply.
func EtcdSnapshotUpload() *EtcdSnapshotUploadApplyConfiguration {
	return &EtcdSnapshotUploadApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *EtcdSnapshotUploadApplyConfiguration) WithNode(value string) *EtcdSnapshotUploadApplyConfiguration {
	b.Node = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *EtcdSnapshotUploadApplyConfiguration) WithName(value string) *EtcdSnapshotUploadApplyConfiguration {
	b.Name = &value
	return b
}

// WithUploadedAt sets the UploadedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UploadedAt field is set to the value of the last call.
func (b *EtcdSnapshotUploadApplyConfiguration) WithUploadedAt(value v1.Time) *EtcdSnapshotUploadApplyConfiguration {
	b.UploadedAt = &value
	return b
}

// WithCheckedAt sets the CheckedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CheckedAt field is set to the value of the last call.
func (b *EtcdSnapshotUploadApplyConfiguration) WithCheckedAt(value v1.Time) *EtcdSnapshotUploadApplyConfiguration {
	b.CheckedAt = &value
	return b
}

// WithStored sets the Stored field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stored field is set to the value of the last call.
func (b *EtcdSnapshotUploadApplyConfiguration) WithStored(value int32) *EtcdSnapshotUploadApplyConfiguration {
	b.Stored = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *EtcdSnapshotUploadApplyConfiguration) WithMessage(value string) *EtcdSnapshotUploadApplyConfiguration {
	b.Message = &value
	return b
}
