// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// EtcdSnapshotSettingsApplyConfiguration represents a declarative configuration of the EtcdSnapshotSettings type for use
// with apply.
//
// EtcdSnapshotSettings schedules k3s etcd snapshots to the bucket.
type EtcdSnapshotSettingsApplyConfiguration struct {
	// Schedule in cron syntax (default every 6 hours).
	Schedule *string `json:"schedule,omitempty"`
	// Retention: how many snapshots to keep (default 28).
	Retention *int32 `json:"retention,omitempty"`
}

// EtcdSnapshotSettingsApplyConfiguration constructs a declarative configuration of the EtcdSnapshotSettings type for use with
// apply.
func EtcdSnapshotSettings() *EtcdSnapshotSettingsApplyConfiguration {
	return &EtcdSnapshotSettingsApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *EtcdSnapshotSettingsApplyConfiguration) WithSchedule(value string) *EtcdSnapshotSettingsApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithRetention sets the Retention field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retention field is set to the value of the last call.
func (b *EtcdSnapshotSettingsApplyConfiguration) WithRetention(value int32) *EtcdSnapshotSettingsApplyConfiguration {
	b.Retention = &value
	return b
}
