// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// FirewallRuleStatusApplyConfiguration represents a declarative configuration of the FirewallRuleStatus type for use
// with apply.
//
// FirewallRuleStatus is written by the firewall reconciler.
type FirewallRuleStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// CloudFirewall reports the Hetzner Cloud Firewall sync for cloud nodes:
	// Applied, Pending (waiting for the rule set to be confirmed on the
	// nodes), Private (pod and private-network traffic, which Cloud
	// Firewalls do not filter), Disabled, Invalid, Off, or empty without a
	// Cloud API token. Written by the Hetzner Cloud reconciler.
	CloudFirewall *string                          `json:"cloudFirewall,omitempty"`
	Conditions    []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// FirewallRuleStatusApplyConfiguration constructs a declarative configuration of the FirewallRuleStatus type for use with
// apply.
func FirewallRuleStatus() *FirewallRuleStatusApplyConfiguration {
	return &FirewallRuleStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *FirewallRuleStatusApplyConfiguration) WithObservedGeneration(value int64) *FirewallRuleStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithCloudFirewall sets the CloudFirewall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudFirewall field is set to the value of the last call.
func (b *FirewallRuleStatusApplyConfiguration) WithCloudFirewall(value string) *FirewallRuleStatusApplyConfiguration {
	b.CloudFirewall = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *FirewallRuleStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *FirewallRuleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
