// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// FirewallRuleSpecApplyConfiguration represents a declarative configuration of the FirewallRuleSpec type for use
// with apply.
//
// FirewallRuleSpec opens a port on the servers themselves (not the apps,
// which the ingress serves). The installer's rules (SSH, HTTP(S), the
// cluster's private ports) are FirewallRules labelled kwerft.dev/required
// that cannot be deleted, only narrowed where safe (SSH sources).
type FirewallRuleSpecApplyConfiguration struct {
	Port     *int32  `json:"port,omitempty"`
	EndPort  *int32  `json:"endPort,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	// Sources allowed in, as CIDRs; empty means anywhere.
	Sources []string `json:"sources,omitempty"`
	// Nodes it applies to: all, or only control-plane nodes.
	Nodes       *string `json:"nodes,omitempty"`
	Description *string `json:"description,omitempty"`
	Disabled    *bool   `json:"disabled,omitempty"`
}

// FirewallRuleSpecApplyConfiguration constructs a declarative configuration of the FirewallRuleSpec type for use with
// apply.
func FirewallRuleSpec() *FirewallRuleSpecApplyConfiguration {
	return &FirewallRuleSpecApplyConfiguration{}
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *FirewallRuleSpecApplyConfiguration) WithPort(value int32) *FirewallRuleSpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithEndPort sets the EndPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndPort field is set to the value of the last call.
func (b *FirewallRuleSpecApplyConfiguration) WithEndPort(value int32) *FirewallRuleSpecApplyConfiguration {
	b.EndPort = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *FirewallRuleSpecApplyConfiguration) WithProtocol(value string) *FirewallRuleSpecApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *FirewallRuleSpecApplyConfiguration) WithSources(values ...string) *FirewallRuleSpecApplyConfiguration {
	for i := range values {
		b.Sources = append(b.Sources, values[i])
	}
	return b
}

// WithNodes sets the Nodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Nodes field is set to the value of the last call.
func (b *FirewallRuleSpecApplyConfiguration) WithNodes(value string) *FirewallRuleSpecApplyConfiguration {
	b.Nodes = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *FirewallRuleSpecApplyConfiguration) WithDescription(value string) *FirewallRuleSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithDisabled sets the Disabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disabled field is set to the value of the last call.
func (b *FirewallRuleSpecApplyConfiguration) WithDisabled(value bool) *FirewallRuleSpecApplyConfiguration {
	b.Disabled = &value
	return b
}
