// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// GitConnectionSpecApplyConfiguration represents a declarative configuration of the GitConnectionSpec type for use
// with apply.
//
// GitConnectionSpec is access to repositories on one Git host. Credentials
// live in the Secret "git-<name>" in the kwerft-builds namespace (keys:
// token, ssh-privatekey, known_hosts, github-app-private-key,
// webhook-secret), which owners and admins may write through the console
// but nobody reads back.
type GitConnectionSpecApplyConfiguration struct {
	Provider *apiv1alpha1.GitProvider `json:"provider,omitempty"`
	// URL of the host, e.g. https://github.com or https://gitlab.example.com.
	URL  *string              `json:"url,omitempty"`
	Auth *apiv1alpha1.GitAuth `json:"auth,omitempty"`
	// Owner limits the connection to one account, organisation or group,
	// e.g. "acme". Empty: whatever the credentials reach.
	Owner     *string                              `json:"owner,omitempty"`
	GitHubApp *GitHubAppSettingsApplyConfiguration `json:"githubApp,omitempty"`
	// Projects that may build with this connection; empty means all.
	Projects []string `json:"projects,omitempty"`
}

// GitConnectionSpecApplyConfiguration constructs a declarative configuration of the GitConnectionSpec type for use with
// apply.
func GitConnectionSpec() *GitConnectionSpecApplyConfiguration {
	return &GitConnectionSpecApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *GitConnectionSpecApplyConfiguration) WithProvider(value apiv1alpha1.GitProvider) *GitConnectionSpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *GitConnectionSpecApplyConfiguration) WithURL(value string) *GitConnectionSpecApplyConfiguration {
	b.URL = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *GitConnectionSpecApplyConfiguration) WithAuth(value apiv1alpha1.GitAuth) *GitConnectionSpecApplyConfiguration {
	b.Auth = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *GitConnectionSpecApplyConfiguration) WithOwner(value string) *GitConnectionSpecApplyConfiguration {
	b.Owner = &value
	return b
}

// WithGitHubApp sets the GitHubApp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GitHubApp field is set to the value of the last call.
func (b *GitConnectionSpecApplyConfiguration) WithGitHubApp(value *GitHubAppSettingsApplyConfiguration) *GitConnectionSpecApplyConfiguration {
	b.GitHubApp = value
	return b
}

// WithProjects adds the given value to the Projects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Projects field.
func (b *GitConnectionSpecApplyConfiguration) WithProjects(values ...string) *GitConnectionSpecApplyConfiguration {
	for i := range values {
		b.Projects = append(b.Projects, values[i])
	}
	return b
}
