// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// GitConnectionStatusApplyConfiguration represents a declarative configuration of the GitConnectionStatus type for use
// with apply.
//
// GitConnectionStatus is written by the GitConnection reconciler.
type GitConnectionStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Account the credentials act as (user, bot or app installation).
	Account *string `json:"account,omitempty"`
	// WebhookURL receives the host's push and pull-request events.
	WebhookURL *string `json:"webhookURL,omitempty"`
	// LastDelivery is when the last valid webhook arrived.
	LastDelivery *v1.Time                             `json:"lastDelivery,omitempty"`
	Conditions   []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// GitConnectionStatusApplyConfiguration constructs a declarative configuration of the GitConnectionStatus type for use with
// apply.
func GitConnectionStatus() *GitConnectionStatusApplyConfiguration {
	return &GitConnectionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithObservedGeneration(value int64) *GitConnectionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithAccount sets the Account field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Account field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithAccount(value string) *GitConnectionStatusApplyConfiguration {
	b.Account = &value
	return b
}

// WithWebhookURL sets the WebhookURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookURL field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithWebhookURL(value string) *GitConnectionStatusApplyConfiguration {
	b.WebhookURL = &value
	return b
}

// WithLastDelivery sets the LastDelivery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastDelivery field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithLastDelivery(value v1.Time) *GitConnectionStatusApplyConfiguration {
	b.LastDelivery = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *GitConnectionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *GitConnectionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
