// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// GitConnectionStatusApplyConfiguration represents a declarative configuration of the GitConnectionStatus type for use
// with apply.
//
// GitConnectionStatus is written by the GitConnection reconciler.
type GitConnectionStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Account the credentials act as (user, bot or app installation).
	Account *string `json:"account,omitempty"`
	// WebhookURL receives the host's push and pull-request events.
	WebhookURL *string `json:"webhookURL,omitempty"`
	// LastDelivery is when the last valid webhook arrived.
	LastDelivery *v1.Time `json:"lastDelivery,omitempty"`
	// WebhookAutomatic: Kwerft sets up the webhooks itself (the GitHub
	// App's own, or one per repository) and none failed. False: add the
	// webhook by hand, with WebhookURL and the webhook secret.
	WebhookAutomatic *bool `json:"webhookAutomatic,omitempty"`
	// Webhooks lists the repositories Apps build from with this connection
	// and whether each has its webhook.
	Webhooks []GitWebhookStatusApplyConfiguration `json:"webhooks,omitempty"`
	// WebhookFingerprint identifies the URL and secret the automatic
	// webhooks were last set to (a truncated hash, not the secret), so a
	// rotated secret or a moved console reaches them.
	WebhookFingerprint *string                              `json:"webhookFingerprint,omitempty"`
	Conditions         []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// GitConnectionStatusApplyConfiguration constructs a declarative configuration of the GitConnectionStatus type for use with
// apply.
func GitConnectionStatus() *GitConnectionStatusApplyConfiguration {
	return &GitConnectionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithObservedGeneration(value int64) *GitConnectionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithAccount sets the Account field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Account field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithAccount(value string) *GitConnectionStatusApplyConfiguration {
	b.Account = &value
	return b
}

// WithWebhookURL sets the WebhookURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookURL field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithWebhookURL(value string) *GitConnectionStatusApplyConfiguration {
	b.WebhookURL = &value
	return b
}

// WithLastDelivery sets the LastDelivery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastDelivery field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithLastDelivery(value v1.Time) *GitConnectionStatusApplyConfiguration {
	b.LastDelivery = &value
	return b
}

// WithWebhookAutomatic sets the WebhookAutomatic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookAutomatic field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithWebhookAutomatic(value bool) *GitConnectionStatusApplyConfiguration {
	b.WebhookAutomatic = &value
	return b
}

// WithWebhooks adds the given value to the Webhooks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Webhooks field.
func (b *GitConnectionStatusApplyConfiguration) WithWebhooks(values ...*GitWebhookStatusApplyConfiguration) *GitConnectionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWebhooks")
		}
		b.Webhooks = append(b.Webhooks, *values[i])
	}
	return b
}

// WithWebhookFingerprint sets the WebhookFingerprint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookFingerprint field is set to the value of the last call.
func (b *GitConnectionStatusApplyConfiguration) WithWebhookFingerprint(value string) *GitConnectionStatusApplyConfiguration {
	b.WebhookFingerprint = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *GitConnectionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *GitConnectionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
