// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// GitHubAppSettingsApplyConfiguration represents a declarative configuration of the GitHubAppSettings type for use
// with apply.
//
// GitHubAppSettings identifies a GitHub App installation. Its private key
// lives in the connection's credentials Secret.
type GitHubAppSettingsApplyConfiguration struct {
	AppID          *int64 `json:"appID,omitempty"`
	InstallationID *int64 `json:"installationID,omitempty"`
	// Slug is the app's URL name, for links to its settings.
	Slug *string `json:"slug,omitempty"`
}

// GitHubAppSettingsApplyConfiguration constructs a declarative configuration of the GitHubAppSettings type for use with
// apply.
func GitHubAppSettings() *GitHubAppSettingsApplyConfiguration {
	return &GitHubAppSettingsApplyConfiguration{}
}

// WithAppID sets the AppID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppID field is set to the value of the last call.
func (b *GitHubAppSettingsApplyConfiguration) WithAppID(value int64) *GitHubAppSettingsApplyConfiguration {
	b.AppID = &value
	return b
}

// WithInstallationID sets the InstallationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallationID field is set to the value of the last call.
func (b *GitHubAppSettingsApplyConfiguration) WithInstallationID(value int64) *GitHubAppSettingsApplyConfiguration {
	b.InstallationID = &value
	return b
}

// WithSlug sets the Slug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Slug field is set to the value of the last call.
func (b *GitHubAppSettingsApplyConfiguration) WithSlug(value string) *GitHubAppSettingsApplyConfiguration {
	b.Slug = &value
	return b
}
