// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// GitSourceApplyConfiguration represents a declarative configuration of the GitSource type for use
// with apply.
//
// GitSource builds the image in-cluster from a Git repository.
type GitSourceApplyConfiguration struct {
	// Repository URL, e.g. https://github.com/acme/api.git or git@host:acme/api.git.
	Repository *string `json:"repository,omitempty"`
	// Branch to build and, with AutoDeploy, to follow.
	Branch *string `json:"branch,omitempty"`
	// Path is the build context inside the repository.
	Path *string `json:"path,omitempty"`
	// Builder selects how the image is built.
	Builder *string `json:"builder,omitempty"`
	// Dockerfile path relative to Path, when Builder is dockerfile.
	Dockerfile *string `json:"dockerfile,omitempty"`
	// Connection names the GitConnection (GitHub App, GitLab, deploy key, ...)
	// that grants access to the repository. Empty for public repositories.
	Connection *string `json:"connection,omitempty"`
	// AutoDeploy builds and deploys every push to Branch.
	AutoDeploy *bool `json:"autoDeploy,omitempty"`
	// PinnedImage runs this image (an earlier build) instead of the latest
	// successful build. The console sets it on rollback; clear it to follow
	// builds again.
	PinnedImage *string `json:"pinnedImage,omitempty"`
}

// GitSourceApplyConfiguration constructs a declarative configuration of the GitSource type for use with
// apply.
func GitSource() *GitSourceApplyConfiguration {
	return &GitSourceApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithRepository(value string) *GitSourceApplyConfiguration {
	b.Repository = &value
	return b
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithBranch(value string) *GitSourceApplyConfiguration {
	b.Branch = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithPath(value string) *GitSourceApplyConfiguration {
	b.Path = &value
	return b
}

// WithBuilder sets the Builder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Builder field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithBuilder(value string) *GitSourceApplyConfiguration {
	b.Builder = &value
	return b
}

// WithDockerfile sets the Dockerfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dockerfile field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithDockerfile(value string) *GitSourceApplyConfiguration {
	b.Dockerfile = &value
	return b
}

// WithConnection sets the Connection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Connection field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithConnection(value string) *GitSourceApplyConfiguration {
	b.Connection = &value
	return b
}

// WithAutoDeploy sets the AutoDeploy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoDeploy field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithAutoDeploy(value bool) *GitSourceApplyConfiguration {
	b.AutoDeploy = &value
	return b
}

// WithPinnedImage sets the PinnedImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PinnedImage field is set to the value of the last call.
func (b *GitSourceApplyConfiguration) WithPinnedImage(value string) *GitSourceApplyConfiguration {
	b.PinnedImage = &value
	return b
}
