// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// GitWebhookStatusApplyConfiguration represents a declarative configuration of the GitWebhookStatus type for use
// with apply.
//
// GitWebhookStatus is the webhook of one repository.
type GitWebhookStatusApplyConfiguration struct {
	Repository *string `json:"repository,omitempty"`
	// Automatic: Kwerft created the webhook and keeps it current.
	Automatic *bool `json:"automatic,omitempty"`
	// Message says what to do when it is not automatic.
	Message *string `json:"message,omitempty"`
}

// GitWebhookStatusApplyConfiguration constructs a declarative configuration of the GitWebhookStatus type for use with
// apply.
func GitWebhookStatus() *GitWebhookStatusApplyConfiguration {
	return &GitWebhookStatusApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *GitWebhookStatusApplyConfiguration) WithRepository(value string) *GitWebhookStatusApplyConfiguration {
	b.Repository = &value
	return b
}

// WithAutomatic sets the Automatic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Automatic field is set to the value of the last call.
func (b *GitWebhookStatusApplyConfiguration) WithAutomatic(value bool) *GitWebhookStatusApplyConfiguration {
	b.Automatic = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *GitWebhookStatusApplyConfiguration) WithMessage(value string) *GitWebhookStatusApplyConfiguration {
	b.Message = &value
	return b
}
