// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// HetznerCloudSettingsApplyConfiguration represents a declarative configuration of the HetznerCloudSettings type for use
// with apply.
//
// HetznerCloudSettings are the Cloud API features owners and admins turn on.
type HetznerCloudSettingsApplyConfiguration struct {
	// Firewall: sync (default) or off.
	Firewall *apiv1alpha1.CloudFirewallMode `json:"firewall,omitempty"`
	// LoadBalancer puts a Hetzner Load Balancer in front of the ingress.
	LoadBalancer *LoadBalancerSettingsApplyConfiguration `json:"loadBalancer,omitempty"`
}

// HetznerCloudSettingsApplyConfiguration constructs a declarative configuration of the HetznerCloudSettings type for use with
// apply.
func HetznerCloudSettings() *HetznerCloudSettingsApplyConfiguration {
	return &HetznerCloudSettingsApplyConfiguration{}
}

// WithFirewall sets the Firewall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Firewall field is set to the value of the last call.
func (b *HetznerCloudSettingsApplyConfiguration) WithFirewall(value apiv1alpha1.CloudFirewallMode) *HetznerCloudSettingsApplyConfiguration {
	b.Firewall = &value
	return b
}

// WithLoadBalancer sets the LoadBalancer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancer field is set to the value of the last call.
func (b *HetznerCloudSettingsApplyConfiguration) WithLoadBalancer(value *LoadBalancerSettingsApplyConfiguration) *HetznerCloudSettingsApplyConfiguration {
	b.LoadBalancer = value
	return b
}
