// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HetznerCloudStatusApplyConfiguration represents a declarative configuration of the HetznerCloudStatus type for use
// with apply.
//
// HetznerCloudStatus is the outcome of the last sync with the Cloud API.
type HetznerCloudStatusApplyConfiguration struct {
	// Servers are this cluster's nodes found in the token's project.
	Servers []CloudServerStatusApplyConfiguration `json:"servers,omitempty"`
	// Firewall is the Cloud Firewall sync.
	Firewall *CloudFirewallStatusApplyConfiguration `json:"firewall,omitempty"`
	// LoadBalancer is the Load Balancer in front of the ingress.
	LoadBalancer *LoadBalancerStatusApplyConfiguration `json:"loadBalancer,omitempty"`
	// Message explains a problem that kept the whole sync from running (no
	// token, token rejected); empty when it ran.
	Message *string `json:"message,omitempty"`
	// SyncedAt is when the Cloud API was last read.
	SyncedAt *v1.Time `json:"syncedAt,omitempty"`
}

// HetznerCloudStatusApplyConfiguration constructs a declarative configuration of the HetznerCloudStatus type for use with
// apply.
func HetznerCloudStatus() *HetznerCloudStatusApplyConfiguration {
	return &HetznerCloudStatusApplyConfiguration{}
}

// WithServers adds the given value to the Servers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Servers field.
func (b *HetznerCloudStatusApplyConfiguration) WithServers(values ...*CloudServerStatusApplyConfiguration) *HetznerCloudStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithServers")
		}
		b.Servers = append(b.Servers, *values[i])
	}
	return b
}

// WithFirewall sets the Firewall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Firewall field is set to the value of the last call.
func (b *HetznerCloudStatusApplyConfiguration) WithFirewall(value *CloudFirewallStatusApplyConfiguration) *HetznerCloudStatusApplyConfiguration {
	b.Firewall = value
	return b
}

// WithLoadBalancer sets the LoadBalancer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancer field is set to the value of the last call.
func (b *HetznerCloudStatusApplyConfiguration) WithLoadBalancer(value *LoadBalancerStatusApplyConfiguration) *HetznerCloudStatusApplyConfiguration {
	b.LoadBalancer = value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *HetznerCloudStatusApplyConfiguration) WithMessage(value string) *HetznerCloudStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithSyncedAt sets the SyncedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SyncedAt field is set to the value of the last call.
func (b *HetznerCloudStatusApplyConfiguration) WithSyncedAt(value v1.Time) *HetznerCloudStatusApplyConfiguration {
	b.SyncedAt = &value
	return b
}
