// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ImageSourceApplyConfiguration represents a declarative configuration of the ImageSource type for use
// with apply.
//
// ImageSource deploys an existing image from any registry.
type ImageSourceApplyConfiguration struct {
	// Ref is a full image reference, e.g. ghcr.io/acme/api:1.42.0.
	Ref *string `json:"ref,omitempty"`
	// PullSecret names a registry credential Secret in the app's namespace.
	PullSecret *string `json:"pullSecret,omitempty"`
}

// ImageSourceApplyConfiguration constructs a declarative configuration of the ImageSource type for use with
// apply.
func ImageSource() *ImageSourceApplyConfiguration {
	return &ImageSourceApplyConfiguration{}
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *ImageSourceApplyConfiguration) WithRef(value string) *ImageSourceApplyConfiguration {
	b.Ref = &value
	return b
}

// WithPullSecret sets the PullSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullSecret field is set to the value of the last call.
func (b *ImageSourceApplyConfiguration) WithPullSecret(value string) *ImageSourceApplyConfiguration {
	b.PullSecret = &value
	return b
}
