// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerSettingsApplyConfiguration represents a declarative configuration of the LoadBalancerSettings type for use
// with apply.
//
// LoadBalancerSettings: a Hetzner Load Balancer that forwards TCP 80 and 443
// (with the PROXY protocol, so the ingress sees client addresses) to the
// cluster's Cloud servers over the private network. While it serves, the
// console's and the apps' DNS records point at it instead of the nodes.
type LoadBalancerSettingsApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
	// Type of the Load Balancer, e.g. lb11 (the default).
	Type *string `json:"type,omitempty"`
	// Location, e.g. fsn1; empty: the location of the cluster's first Cloud
	// server.
	Location *string `json:"location,omitempty"`
}

// LoadBalancerSettingsApplyConfiguration constructs a declarative configuration of the LoadBalancerSettings type for use with
// apply.
func LoadBalancerSettings() *LoadBalancerSettingsApplyConfiguration {
	return &LoadBalancerSettingsApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *LoadBalancerSettingsApplyConfiguration) WithEnabled(value bool) *LoadBalancerSettingsApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *LoadBalancerSettingsApplyConfiguration) WithType(value string) *LoadBalancerSettingsApplyConfiguration {
	b.Type = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *LoadBalancerSettingsApplyConfiguration) WithLocation(value string) *LoadBalancerSettingsApplyConfiguration {
	b.Location = &value
	return b
}
