// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LoadBalancerStatusApplyConfiguration represents a declarative configuration of the LoadBalancerStatus type for use
// with apply.
//
// LoadBalancerStatus reports the Load Balancer in front of the ingress.
type LoadBalancerStatusApplyConfiguration struct {
	// State: Creating, Waiting (no healthy target yet), Active, Draining
	// (turned off; deleted once DNS moved back), Error.
	State *string `json:"state,omitempty"`
	// Active: DNS points at the Load Balancer (status.publicAddresses).
	Active   *bool   `json:"active,omitempty"`
	ID       *int64  `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Type     *string `json:"type,omitempty"`
	Location *string `json:"location,omitempty"`
	IPv4     *string `json:"ipv4,omitempty"`
	IPv6     *string `json:"ipv6,omitempty"`
	// Targets the Load Balancer forwards to, and how many of them pass the
	// health checks on 443.
	Targets        *int32 `json:"targets,omitempty"`
	HealthyTargets *int32 `json:"healthyTargets,omitempty"`
	// DrainingSince is when it was turned off; it is deleted DNS TTLs later.
	DrainingSince *v1.Time `json:"drainingSince,omitempty"`
	Message       *string  `json:"message,omitempty"`
}

// LoadBalancerStatusApplyConfiguration constructs a declarative configuration of the LoadBalancerStatus type for use with
// apply.
func LoadBalancerStatus() *LoadBalancerStatusApplyConfiguration {
	return &LoadBalancerStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithState(value string) *LoadBalancerStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithActive(value bool) *LoadBalancerStatusApplyConfiguration {
	b.Active = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithID(value int64) *LoadBalancerStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithName(value string) *LoadBalancerStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithType(value string) *LoadBalancerStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithLocation(value string) *LoadBalancerStatusApplyConfiguration {
	b.Location = &value
	return b
}

// WithIPv4 sets the IPv4 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPv4 field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithIPv4(value string) *LoadBalancerStatusApplyConfiguration {
	b.IPv4 = &value
	return b
}

// WithIPv6 sets the IPv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPv6 field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithIPv6(value string) *LoadBalancerStatusApplyConfiguration {
	b.IPv6 = &value
	return b
}

// WithTargets sets the Targets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Targets field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithTargets(value int32) *LoadBalancerStatusApplyConfiguration {
	b.Targets = &value
	return b
}

// WithHealthyTargets sets the HealthyTargets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthyTargets field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithHealthyTargets(value int32) *LoadBalancerStatusApplyConfiguration {
	b.HealthyTargets = &value
	return b
}

// WithDrainingSince sets the DrainingSince field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DrainingSince field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithDrainingSince(value v1.Time) *LoadBalancerStatusApplyConfiguration {
	b.DrainingSince = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *LoadBalancerStatusApplyConfiguration) WithMessage(value string) *LoadBalancerStatusApplyConfiguration {
	b.Message = &value
	return b
}
