// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MaintenanceWindowApplyConfiguration represents a declarative configuration of the MaintenanceWindow type for use
// with apply.
//
// MaintenanceWindow is when automatic upgrades may start.
type MaintenanceWindowApplyConfiguration struct {
	// Days of the week (Mon … Sun); empty: every day.
	Days []string `json:"days,omitempty"`
	// Start as HH:MM in TimeZone.
	Start    *string      `json:"start,omitempty"`
	Duration *v1.Duration `json:"duration,omitempty"`
	// TimeZone, an IANA name (default UTC).
	TimeZone *string `json:"timeZone,omitempty"`
}

// MaintenanceWindowApplyConfiguration constructs a declarative configuration of the MaintenanceWindow type for use with
// apply.
func MaintenanceWindow() *MaintenanceWindowApplyConfiguration {
	return &MaintenanceWindowApplyConfiguration{}
}

// WithDays adds the given value to the Days field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Days field.
func (b *MaintenanceWindowApplyConfiguration) WithDays(values ...string) *MaintenanceWindowApplyConfiguration {
	for i := range values {
		b.Days = append(b.Days, values[i])
	}
	return b
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *MaintenanceWindowApplyConfiguration) WithStart(value string) *MaintenanceWindowApplyConfiguration {
	b.Start = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *MaintenanceWindowApplyConfiguration) WithDuration(value v1.Duration) *MaintenanceWindowApplyConfiguration {
	b.Duration = &value
	return b
}

// WithTimeZone sets the TimeZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeZone field is set to the value of the last call.
func (b *MaintenanceWindowApplyConfiguration) WithTimeZone(value string) *MaintenanceWindowApplyConfiguration {
	b.TimeZone = &value
	return b
}
