// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NodePoolSpecApplyConfiguration represents a declarative configuration of the NodePoolSpec type for use
// with apply.
//
// NodePoolSpec is a group of Hetzner Cloud servers Kwerft keeps as nodes of
// one cluster.
type NodePoolSpecApplyConfiguration struct {
	// Cluster the nodes join ("local" for the management cluster).
	Cluster *string               `json:"cluster,omitempty"`
	Role    *apiv1alpha1.NodeRole `json:"role,omitempty"`
	// ServerType, e.g. cx32. Changing it replaces nodes one at a time.
	ServerType *string `json:"serverType,omitempty"`
	// Location, e.g. fsn1; must be in the cluster's network zone.
	Location *string `json:"location,omitempty"`
	// Count of servers. For role builds it is the maximum; the pool scales
	// to zero when no build has run for ScaleDownAfter.
	Count          *int32       `json:"count,omitempty"`
	ScaleDownAfter *v1.Duration `json:"scaleDownAfter,omitempty"`
	// Labels put on the pool's Kubernetes nodes.
	Labels map[string]string `json:"labels,omitempty"`
}

// NodePoolSpecApplyConfiguration constructs a declarative configuration of the NodePoolSpec type for use with
// apply.
func NodePoolSpec() *NodePoolSpecApplyConfiguration {
	return &NodePoolSpecApplyConfiguration{}
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithCluster(value string) *NodePoolSpecApplyConfiguration {
	b.Cluster = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithRole(value apiv1alpha1.NodeRole) *NodePoolSpecApplyConfiguration {
	b.Role = &value
	return b
}

// WithServerType sets the ServerType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerType field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithServerType(value string) *NodePoolSpecApplyConfiguration {
	b.ServerType = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithLocation(value string) *NodePoolSpecApplyConfiguration {
	b.Location = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithCount(value int32) *NodePoolSpecApplyConfiguration {
	b.Count = &value
	return b
}

// WithScaleDownAfter sets the ScaleDownAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScaleDownAfter field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithScaleDownAfter(value v1.Duration) *NodePoolSpecApplyConfiguration {
	b.ScaleDownAfter = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *NodePoolSpecApplyConfiguration) WithLabels(entries map[string]string) *NodePoolSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}
