// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NotificationChannelStatusApplyConfiguration represents a declarative configuration of the NotificationChannelStatus type for use
// with apply.
//
// NotificationChannelStatus is written by the alerting reconciler.
type NotificationChannelStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// SecretSet says the channel's Secret holds what its type needs (the
	// webhook URL, the SMTP password, the ntfy token); never the values.
	SecretSet *bool `json:"secretSet,omitempty"`
	// LastTest is when the console last sent a test notification, and how it went.
	LastTest      *v1.Time                             `json:"lastTest,omitempty"`
	LastTestError *string                              `json:"lastTestError,omitempty"`
	Conditions    []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// NotificationChannelStatusApplyConfiguration constructs a declarative configuration of the NotificationChannelStatus type for use with
// apply.
func NotificationChannelStatus() *NotificationChannelStatusApplyConfiguration {
	return &NotificationChannelStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *NotificationChannelStatusApplyConfiguration) WithObservedGeneration(value int64) *NotificationChannelStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithSecretSet sets the SecretSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretSet field is set to the value of the last call.
func (b *NotificationChannelStatusApplyConfiguration) WithSecretSet(value bool) *NotificationChannelStatusApplyConfiguration {
	b.SecretSet = &value
	return b
}

// WithLastTest sets the LastTest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTest field is set to the value of the last call.
func (b *NotificationChannelStatusApplyConfiguration) WithLastTest(value v1.Time) *NotificationChannelStatusApplyConfiguration {
	b.LastTest = &value
	return b
}

// WithLastTestError sets the LastTestError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTestError field is set to the value of the last call.
func (b *NotificationChannelStatusApplyConfiguration) WithLastTestError(value string) *NotificationChannelStatusApplyConfiguration {
	b.LastTestError = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *NotificationChannelStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *NotificationChannelStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
