// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// NotificationChannelSpecApplyConfiguration represents a declarative configuration of the NotificationChannelSpec type for use
// with apply.
//
// NotificationChannelSpec is one place alerts go. Secrets (webhook URLs,
// passwords, tokens) live in the Secret "notify-<name>" in
// kwerft-observability, written by owners and admins through the console and
// read back by nobody.
type NotificationChannelSpecApplyConfiguration struct {
	Type    *apiv1alpha1.NotificationType    `json:"type,omitempty"`
	Slack   *SlackSettingsApplyConfiguration `json:"slack,omitempty"`
	Email   *EmailSettingsApplyConfiguration `json:"email,omitempty"`
	Webhook *apiv1alpha1.WebhookSettings     `json:"webhook,omitempty"`
	Ntfy    *NtfySettingsApplyConfiguration  `json:"ntfy,omitempty"`
	// SendResolved also notifies when an alert stops firing.
	SendResolved *bool `json:"sendResolved,omitempty"`
}

// NotificationChannelSpecApplyConfiguration constructs a declarative configuration of the NotificationChannelSpec type for use with
// apply.
func NotificationChannelSpec() *NotificationChannelSpecApplyConfiguration {
	return &NotificationChannelSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *NotificationChannelSpecApplyConfiguration) WithType(value apiv1alpha1.NotificationType) *NotificationChannelSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithSlack sets the Slack field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Slack field is set to the value of the last call.
func (b *NotificationChannelSpecApplyConfiguration) WithSlack(value *SlackSettingsApplyConfiguration) *NotificationChannelSpecApplyConfiguration {
	b.Slack = value
	return b
}

// WithEmail sets the Email field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Email field is set to the value of the last call.
func (b *NotificationChannelSpecApplyConfiguration) WithEmail(value *EmailSettingsApplyConfiguration) *NotificationChannelSpecApplyConfiguration {
	b.Email = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *NotificationChannelSpecApplyConfiguration) WithWebhook(value apiv1alpha1.WebhookSettings) *NotificationChannelSpecApplyConfiguration {
	b.Webhook = &value
	return b
}

// WithNtfy sets the Ntfy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ntfy field is set to the value of the last call.
func (b *NotificationChannelSpecApplyConfiguration) WithNtfy(value *NtfySettingsApplyConfiguration) *NotificationChannelSpecApplyConfiguration {
	b.Ntfy = value
	return b
}

// WithSendResolved sets the SendResolved field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SendResolved field is set to the value of the last call.
func (b *NotificationChannelSpecApplyConfiguration) WithSendResolved(value bool) *NotificationChannelSpecApplyConfiguration {
	b.SendResolved = &value
	return b
}
