// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NtfySettingsApplyConfiguration represents a declarative configuration of the NtfySettings type for use
// with apply.
//
// NtfySettings: an optional access token is secret (key "token").
type NtfySettingsApplyConfiguration struct {
	Server *string `json:"server,omitempty"`
	Topic  *string `json:"topic,omitempty"`
}

// NtfySettingsApplyConfiguration constructs a declarative configuration of the NtfySettings type for use with
// apply.
func NtfySettings() *NtfySettingsApplyConfiguration {
	return &NtfySettingsApplyConfiguration{}
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *NtfySettingsApplyConfiguration) WithServer(value string) *NtfySettingsApplyConfiguration {
	b.Server = &value
	return b
}

// WithTopic sets the Topic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Topic field is set to the value of the last call.
func (b *NtfySettingsApplyConfiguration) WithTopic(value string) *NtfySettingsApplyConfiguration {
	b.Topic = &value
	return b
}
