// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PoolNodeApplyConfiguration represents a declarative configuration of the PoolNode type for use
// with apply.
//
// PoolNode is one server of a NodePool.
type PoolNodeApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	ServerID  *int64  `json:"serverID,omitempty"`
	PublicIP  *string `json:"publicIP,omitempty"`
	PrivateIP *string `json:"privateIP,omitempty"`
	// Phase: Creating, Joining, Ready, Draining, Deleting, Failed.
	Phase   *string `json:"phase,omitempty"`
	Message *string `json:"message,omitempty"`
}

// PoolNodeApplyConfiguration constructs a declarative configuration of the PoolNode type for use with
// apply.
func PoolNode() *PoolNodeApplyConfiguration {
	return &PoolNodeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PoolNodeApplyConfiguration) WithName(value string) *PoolNodeApplyConfiguration {
	b.Name = &value
	return b
}

// WithServerID sets the ServerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerID field is set to the value of the last call.
func (b *PoolNodeApplyConfiguration) WithServerID(value int64) *PoolNodeApplyConfiguration {
	b.ServerID = &value
	return b
}

// WithPublicIP sets the PublicIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicIP field is set to the value of the last call.
func (b *PoolNodeApplyConfiguration) WithPublicIP(value string) *PoolNodeApplyConfiguration {
	b.PublicIP = &value
	return b
}

// WithPrivateIP sets the PrivateIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateIP field is set to the value of the last call.
func (b *PoolNodeApplyConfiguration) WithPrivateIP(value string) *PoolNodeApplyConfiguration {
	b.PrivateIP = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *PoolNodeApplyConfiguration) WithPhase(value string) *PoolNodeApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PoolNodeApplyConfiguration) WithMessage(value string) *PoolNodeApplyConfiguration {
	b.Message = &value
	return b
}
