// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ProjectSpecApplyConfiguration represents a declarative configuration of the ProjectSpec type for use
// with apply.
//
// ProjectSpec describes a group of apps that share a namespace, quotas and
// access rules.
type ProjectSpecApplyConfiguration struct {
	// DisplayName is shown in the console; the resource name is the namespace.
	DisplayName *string `json:"displayName,omitempty"`
	// Quota caps the total resources the project may request.
	// Keys: requests.cpu, requests.memory, requests.storage, ...
	Quota *v1.ResourceList `json:"quota,omitempty"`
	// PodSecurity is the Pod Security Admission level enforced in the namespace.
	PodSecurity *string `json:"podSecurity,omitempty"`
	// Isolated denies traffic from other projects unless a TrafficRule allows it.
	Isolated *bool `json:"isolated,omitempty"`
}

// ProjectSpecApplyConfiguration constructs a declarative configuration of the ProjectSpec type for use with
// apply.
func ProjectSpec() *ProjectSpecApplyConfiguration {
	return &ProjectSpecApplyConfiguration{}
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *ProjectSpecApplyConfiguration) WithDisplayName(value string) *ProjectSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithQuota sets the Quota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quota field is set to the value of the last call.
func (b *ProjectSpecApplyConfiguration) WithQuota(value v1.ResourceList) *ProjectSpecApplyConfiguration {
	b.Quota = &value
	return b
}

// WithPodSecurity sets the PodSecurity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSecurity field is set to the value of the last call.
func (b *ProjectSpecApplyConfiguration) WithPodSecurity(value string) *ProjectSpecApplyConfiguration {
	b.PodSecurity = &value
	return b
}

// WithIsolated sets the Isolated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Isolated field is set to the value of the last call.
func (b *ProjectSpecApplyConfiguration) WithIsolated(value bool) *ProjectSpecApplyConfiguration {
	b.Isolated = &value
	return b
}
