// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ProjectMemberApplyConfiguration represents a declarative configuration of the ProjectMember type for use
// with apply.
//
// ProjectMember is a console user's role in one project.
type ProjectMemberApplyConfiguration struct {
	// User is the console user's email address.
	User *string `json:"user,omitempty"`
	Role *string `json:"role,omitempty"`
}

// ProjectMemberApplyConfiguration constructs a declarative configuration of the ProjectMember type for use with
// apply.
func ProjectMember() *ProjectMemberApplyConfiguration {
	return &ProjectMemberApplyConfiguration{}
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *ProjectMemberApplyConfiguration) WithUser(value string) *ProjectMemberApplyConfiguration {
	b.User = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *ProjectMemberApplyConfiguration) WithRole(value string) *ProjectMemberApplyConfiguration {
	b.Role = &value
	return b
}
