// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ProjectStatusApplyConfiguration represents a declarative configuration of the ProjectStatus type for use
// with apply.
//
// ProjectStatus is written by the Project reconciler.
type ProjectStatusApplyConfiguration struct {
	ObservedGeneration *int64                           `json:"observedGeneration,omitempty"`
	Conditions         []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ProjectStatusApplyConfiguration constructs a declarative configuration of the ProjectStatus type for use with
// apply.
func ProjectStatus() *ProjectStatusApplyConfiguration {
	return &ProjectStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ProjectStatusApplyConfiguration) WithObservedGeneration(value int64) *ProjectStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ProjectStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ProjectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
