// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RestoreStatusApplyConfiguration represents a declarative configuration of the RestoreStatus type for use
// with apply.
//
// RestoreStatus is written by the Restore reconciler.
type RestoreStatusApplyConfiguration struct {
	// Phase: Pending, InProgress, Completed, PartiallyFailed, Failed.
	Phase *string `json:"phase,omitempty"`
	// VeleroRestore is the Velero Restore's name.
	VeleroRestore *string                              `json:"veleroRestore,omitempty"`
	StartedAt     *v1.Time                             `json:"startedAt,omitempty"`
	CompletedAt   *v1.Time                             `json:"completedAt,omitempty"`
	Warnings      *int32                               `json:"warnings,omitempty"`
	Errors        *int32                               `json:"errors,omitempty"`
	Message       *string                              `json:"message,omitempty"`
	Conditions    []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RestoreStatusApplyConfiguration constructs a declarative configuration of the RestoreStatus type for use with
// apply.
func RestoreStatus() *RestoreStatusApplyConfiguration {
	return &RestoreStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *RestoreStatusApplyConfiguration) WithPhase(value string) *RestoreStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithVeleroRestore sets the VeleroRestore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VeleroRestore field is set to the value of the last call.
func (b *RestoreStatusApplyConfiguration) WithVeleroRestore(value string) *RestoreStatusApplyConfiguration {
	b.VeleroRestore = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *RestoreStatusApplyConfiguration) WithStartedAt(value v1.Time) *RestoreStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *RestoreStatusApplyConfiguration) WithCompletedAt(value v1.Time) *RestoreStatusApplyConfiguration {
	b.CompletedAt = &value
	return b
}

// WithWarnings sets the Warnings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Warnings field is set to the value of the last call.
func (b *RestoreStatusApplyConfiguration) WithWarnings(value int32) *RestoreStatusApplyConfiguration {
	b.Warnings = &value
	return b
}

// WithErrors sets the Errors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Errors field is set to the value of the last call.
func (b *RestoreStatusApplyConfiguration) WithErrors(value int32) *RestoreStatusApplyConfiguration {
	b.Errors = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *RestoreStatusApplyConfiguration) WithMessage(value string) *RestoreStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RestoreStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *RestoreStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
