// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RestoreSpecApplyConfiguration represents a declarative configuration of the RestoreSpec type for use
// with apply.
//
// RestoreSpec brings a project, or some of its Apps, back from a backup.
// A whole cluster is restored by install.sh --restore on a new server, not
// by a Restore.
type RestoreSpecApplyConfiguration struct {
	// Backup is the Velero Backup's name.
	Backup *string `json:"backup,omitempty"`
	// Project to restore from the backup.
	Project *string `json:"project,omitempty"`
	// TargetProject restores under another name, next to the original
	// (a new project); empty: into the original project, replacing only
	// objects that no longer exist.
	TargetProject *string `json:"targetProject,omitempty"`
	// Apps limits the restore to these Apps with their Volumes, SecretSets
	// and Domains; empty: the whole project.
	Apps []string `json:"apps,omitempty"`
}

// RestoreSpecApplyConfiguration constructs a declarative configuration of the RestoreSpec type for use with
// apply.
func RestoreSpec() *RestoreSpecApplyConfiguration {
	return &RestoreSpecApplyConfiguration{}
}

// WithBackup sets the Backup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backup field is set to the value of the last call.
func (b *RestoreSpecApplyConfiguration) WithBackup(value string) *RestoreSpecApplyConfiguration {
	b.Backup = &value
	return b
}

// WithProject sets the Project field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Project field is set to the value of the last call.
func (b *RestoreSpecApplyConfiguration) WithProject(value string) *RestoreSpecApplyConfiguration {
	b.Project = &value
	return b
}

// WithTargetProject sets the TargetProject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetProject field is set to the value of the last call.
func (b *RestoreSpecApplyConfiguration) WithTargetProject(value string) *RestoreSpecApplyConfiguration {
	b.TargetProject = &value
	return b
}

// WithApps adds the given value to the Apps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Apps field.
func (b *RestoreSpecApplyConfiguration) WithApps(values ...string) *RestoreSpecApplyConfiguration {
	for i := range values {
		b.Apps = append(b.Apps, values[i])
	}
	return b
}
