// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ScheduleStatusApplyConfiguration represents a declarative configuration of the ScheduleStatus type for use
// with apply.
//
// ScheduleStatus is written by the Schedule reconciler.
type ScheduleStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// LastScheduleTime is the scheduled time of the most recent run started.
	LastScheduleTime *v1.Time `json:"lastScheduleTime,omitempty"`
	// NextScheduleTime is when the next run is due; empty while suspended.
	NextScheduleTime *v1.Time `json:"nextScheduleTime,omitempty"`
	// LastSuccessTime is when a run last succeeded.
	LastSuccessTime *v1.Time `json:"lastSuccessTime,omitempty"`
	// LastFailureTime is when a run last failed.
	LastFailureTime *v1.Time `json:"lastFailureTime,omitempty"`
	// Active lists the Tasks of this Schedule that have not finished.
	Active     []string                             `json:"active,omitempty"`
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ScheduleStatusApplyConfiguration constructs a declarative configuration of the ScheduleStatus type for use with
// apply.
func ScheduleStatus() *ScheduleStatusApplyConfiguration {
	return &ScheduleStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ScheduleStatusApplyConfiguration) WithObservedGeneration(value int64) *ScheduleStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithLastScheduleTime sets the LastScheduleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScheduleTime field is set to the value of the last call.
func (b *ScheduleStatusApplyConfiguration) WithLastScheduleTime(value v1.Time) *ScheduleStatusApplyConfiguration {
	b.LastScheduleTime = &value
	return b
}

// WithNextScheduleTime sets the NextScheduleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextScheduleTime field is set to the value of the last call.
func (b *ScheduleStatusApplyConfiguration) WithNextScheduleTime(value v1.Time) *ScheduleStatusApplyConfiguration {
	b.NextScheduleTime = &value
	return b
}

// WithLastSuccessTime sets the LastSuccessTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessTime field is set to the value of the last call.
func (b *ScheduleStatusApplyConfiguration) WithLastSuccessTime(value v1.Time) *ScheduleStatusApplyConfiguration {
	b.LastSuccessTime = &value
	return b
}

// WithLastFailureTime sets the LastFailureTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastFailureTime field is set to the value of the last call.
func (b *ScheduleStatusApplyConfiguration) WithLastFailureTime(value v1.Time) *ScheduleStatusApplyConfiguration {
	b.LastFailureTime = &value
	return b
}

// WithActive adds the given value to the Active field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Active field.
func (b *ScheduleStatusApplyConfiguration) WithActive(values ...string) *ScheduleStatusApplyConfiguration {
	for i := range values {
		b.Active = append(b.Active, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ScheduleStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ScheduleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
