// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ScheduleSpecApplyConfiguration represents a declarative configuration of the ScheduleSpec type for use
// with apply.
//
// ScheduleSpec runs a Task on a cron schedule.
type ScheduleSpecApplyConfiguration struct {
	// Schedule in cron format: "minute hour day-of-month month day-of-week"
	// (e.g. "30 3 * * *"), or @hourly, @daily, @weekly, @monthly, @yearly,
	// @every 2h.
	Schedule *string `json:"schedule,omitempty"`
	// TimeZone is an IANA name such as Europe/Berlin. Empty means the time
	// zone of the Kwerft server process, which is UTC in its container.
	TimeZone *string `json:"timeZone,omitempty"`
	// Suspend stops new runs; running ones continue.
	Suspend *bool `json:"suspend,omitempty"`
	// Concurrency when a run is due while an earlier one still runs:
	// Forbid (wait, see startingDeadline), Replace or Allow.
	Concurrency *string `json:"concurrency,omitempty"`
	// StartingDeadline is how late a run may still start: after Kwerft was
	// down, while the schedule was suspended, or while Forbid waited for an
	// earlier run. Of several missed runs only the latest starts. Default 1h.
	StartingDeadline *v1.Duration `json:"startingDeadline,omitempty"`
	// History is how many finished Tasks to keep.
	History *ScheduleHistoryApplyConfiguration `json:"history,omitempty"`
	// Task is the template for every run.
	Task *TaskSpecApplyConfiguration `json:"task,omitempty"`
}

// ScheduleSpecApplyConfiguration constructs a declarative configuration of the ScheduleSpec type for use with
// apply.
func ScheduleSpec() *ScheduleSpecApplyConfiguration {
	return &ScheduleSpecApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithSchedule(value string) *ScheduleSpecApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithTimeZone sets the TimeZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeZone field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithTimeZone(value string) *ScheduleSpecApplyConfiguration {
	b.TimeZone = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithSuspend(value bool) *ScheduleSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithConcurrency sets the Concurrency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Concurrency field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithConcurrency(value string) *ScheduleSpecApplyConfiguration {
	b.Concurrency = &value
	return b
}

// WithStartingDeadline sets the StartingDeadline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartingDeadline field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithStartingDeadline(value v1.Duration) *ScheduleSpecApplyConfiguration {
	b.StartingDeadline = &value
	return b
}

// WithHistory sets the History field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the History field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithHistory(value *ScheduleHistoryApplyConfiguration) *ScheduleSpecApplyConfiguration {
	b.History = value
	return b
}

// WithTask sets the Task field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Task field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithTask(value *TaskSpecApplyConfiguration) *ScheduleSpecApplyConfiguration {
	b.Task = value
	return b
}
