// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SecretSetStatusApplyConfiguration represents a declarative configuration of the SecretSetStatus type for use
// with apply.
//
// SecretSetStatus is written by the SecretSet reconciler with the
// controller's own permissions, so developers and viewers learn key names
// without reading the Secret.
type SecretSetStatusApplyConfiguration struct {
	ObservedGeneration *int64                              `json:"observedGeneration,omitempty"`
	Keys               []SecretKeyStatusApplyConfiguration `json:"keys,omitempty"`
	// UsedBy lists the Apps, Tasks and Schedules that reference this set,
	// as "App/api".
	UsedBy []string `json:"usedBy,omitempty"`
	// Missing lists references to keys the set does not have, as
	// "App/api: SMTP_PASSWORD".
	Missing    []string                         `json:"missing,omitempty"`
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SecretSetStatusApplyConfiguration constructs a declarative configuration of the SecretSetStatus type for use with
// apply.
func SecretSetStatus() *SecretSetStatusApplyConfiguration {
	return &SecretSetStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *SecretSetStatusApplyConfiguration) WithObservedGeneration(value int64) *SecretSetStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithKeys adds the given value to the Keys field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Keys field.
func (b *SecretSetStatusApplyConfiguration) WithKeys(values ...*SecretKeyStatusApplyConfiguration) *SecretSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithKeys")
		}
		b.Keys = append(b.Keys, *values[i])
	}
	return b
}

// WithUsedBy adds the given value to the UsedBy field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UsedBy field.
func (b *SecretSetStatusApplyConfiguration) WithUsedBy(values ...string) *SecretSetStatusApplyConfiguration {
	for i := range values {
		b.UsedBy = append(b.UsedBy, values[i])
	}
	return b
}

// WithMissing adds the given value to the Missing field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Missing field.
func (b *SecretSetStatusApplyConfiguration) WithMissing(values ...string) *SecretSetStatusApplyConfiguration {
	for i := range values {
		b.Missing = append(b.Missing, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SecretSetStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SecretSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
