// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SecretKeyStatusApplyConfiguration represents a declarative configuration of the SecretKeyStatus type for use
// with apply.
//
// SecretKeyStatus describes one key, never its value.
type SecretKeyStatusApplyConfiguration struct {
	Name      *string  `json:"name,omitempty"`
	UpdatedAt *v1.Time `json:"updatedAt,omitempty"`
	// UpdatedBy is the console user who last set it; empty for generated
	// and derived keys.
	UpdatedBy *string `json:"updatedBy,omitempty"`
	// Source: Set, Generated or Derived.
	Source *string `json:"source,omitempty"`
}

// SecretKeyStatusApplyConfiguration constructs a declarative configuration of the SecretKeyStatus type for use with
// apply.
func SecretKeyStatus() *SecretKeyStatusApplyConfiguration {
	return &SecretKeyStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SecretKeyStatusApplyConfiguration) WithName(value string) *SecretKeyStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithUpdatedAt sets the UpdatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedAt field is set to the value of the last call.
func (b *SecretKeyStatusApplyConfiguration) WithUpdatedAt(value v1.Time) *SecretKeyStatusApplyConfiguration {
	b.UpdatedAt = &value
	return b
}

// WithUpdatedBy sets the UpdatedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedBy field is set to the value of the last call.
func (b *SecretKeyStatusApplyConfiguration) WithUpdatedBy(value string) *SecretKeyStatusApplyConfiguration {
	b.UpdatedBy = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *SecretKeyStatusApplyConfiguration) WithSource(value string) *SecretKeyStatusApplyConfiguration {
	b.Source = &value
	return b
}
