// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SecretSetSpecApplyConfiguration represents a declarative configuration of the SecretSetSpec type for use
// with apply.
//
// SecretSetSpec is a named group of secret values in a project (docs/plan.md
// › Secrets). The values live in the Secret of the same name, labelled
// kwerft.dev/secret-set, which the API writes as the user; the spec holds
// no values.
type SecretSetSpecApplyConfiguration struct {
	Description *string `json:"description,omitempty"`
	// Generate lists keys the reconciler fills with 32 random bytes
	// (base64url) while they are missing, e.g. a database password from a
	// template. Removing a key here keeps its value.
	Generate []string `json:"generate,omitempty"`
	// Derived keys are computed from other keys of the set by the
	// reconciler, e.g. DATABASE_URL from PASSWORD.
	Derived []DerivedSecretKeyApplyConfiguration `json:"derived,omitempty"`
}

// SecretSetSpecApplyConfiguration constructs a declarative configuration of the SecretSetSpec type for use with
// apply.
func SecretSetSpec() *SecretSetSpecApplyConfiguration {
	return &SecretSetSpecApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *SecretSetSpecApplyConfiguration) WithDescription(value string) *SecretSetSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithGenerate adds the given value to the Generate field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Generate field.
func (b *SecretSetSpecApplyConfiguration) WithGenerate(values ...string) *SecretSetSpecApplyConfiguration {
	for i := range values {
		b.Generate = append(b.Generate, values[i])
	}
	return b
}

// WithDerived adds the given value to the Derived field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Derived field.
func (b *SecretSetSpecApplyConfiguration) WithDerived(values ...*DerivedSecretKeyApplyConfiguration) *SecretSetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDerived")
		}
		b.Derived = append(b.Derived, *values[i])
	}
	return b
}
