// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SlackSettingsApplyConfiguration represents a declarative configuration of the SlackSettings type for use
// with apply.
//
// SlackSettings: the incoming-webhook URL is secret (key "url").
type SlackSettingsApplyConfiguration struct {
	// Channel to post to, e.g. #ops-alerts; empty uses the webhook's default.
	Channel *string `json:"channel,omitempty"`
}

// SlackSettingsApplyConfiguration constructs a declarative configuration of the SlackSettings type for use with
// apply.
func SlackSettings() *SlackSettingsApplyConfiguration {
	return &SlackSettingsApplyConfiguration{}
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *SlackSettingsApplyConfiguration) WithChannel(value string) *SlackSettingsApplyConfiguration {
	b.Channel = &value
	return b
}
