// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SSOSettingsApplyConfiguration represents a declarative configuration of the SSOSettings type for use
// with apply.
//
// SSOSettings configures "Sign in with …" on the console's sign-in page.
// Users are matched by the email address the provider verified; a first
// sign-in links the provider account to the user.
type SSOSettingsApplyConfiguration struct {
	// Enabled shows the button on the sign-in page.
	Enabled *bool `json:"enabled,omitempty"`
	// Provider is the preset: google, microsoft (Entra ID, one tenant),
	// keycloak or oidc (any OpenID Connect provider).
	Provider *string `json:"provider,omitempty"`
	// Issuer is the provider's issuer URL; discovery reads
	// <issuer>/.well-known/openid-configuration.
	Issuer *string `json:"issuer,omitempty"`
	// ClientID of the console's OAuth client at the provider.
	ClientID *string `json:"clientID,omitempty"`
	// DisplayName names the provider on the button ("Sign in with …").
	DisplayName *string `json:"displayName,omitempty"`
	// AllowedDomains, when set, admits only email addresses in these
	// domains. Auto-join requires it.
	AllowedDomains []string `json:"allowedDomains,omitempty"`
	// AutoJoin creates an account with DefaultRole for a verified address
	// in AllowedDomains on its first sign-in. Off: only existing members and
	// people with an open invite can sign in.
	AutoJoin *bool `json:"autoJoin,omitempty"`
	// DefaultRole for auto-joined accounts.
	DefaultRole *string `json:"defaultRole,omitempty"`
}

// SSOSettingsApplyConfiguration constructs a declarative configuration of the SSOSettings type for use with
// apply.
func SSOSettings() *SSOSettingsApplyConfiguration {
	return &SSOSettingsApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SSOSettingsApplyConfiguration) WithEnabled(value bool) *SSOSettingsApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *SSOSettingsApplyConfiguration) WithProvider(value string) *SSOSettingsApplyConfiguration {
	b.Provider = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *SSOSettingsApplyConfiguration) WithIssuer(value string) *SSOSettingsApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *SSOSettingsApplyConfiguration) WithClientID(value string) *SSOSettingsApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *SSOSettingsApplyConfiguration) WithDisplayName(value string) *SSOSettingsApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithAllowedDomains adds the given value to the AllowedDomains field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedDomains field.
func (b *SSOSettingsApplyConfiguration) WithAllowedDomains(values ...string) *SSOSettingsApplyConfiguration {
	for i := range values {
		b.AllowedDomains = append(b.AllowedDomains, values[i])
	}
	return b
}

// WithAutoJoin sets the AutoJoin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoJoin field is set to the value of the last call.
func (b *SSOSettingsApplyConfiguration) WithAutoJoin(value bool) *SSOSettingsApplyConfiguration {
	b.AutoJoin = &value
	return b
}

// WithDefaultRole sets the DefaultRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultRole field is set to the value of the last call.
func (b *SSOSettingsApplyConfiguration) WithDefaultRole(value string) *SSOSettingsApplyConfiguration {
	b.DefaultRole = &value
	return b
}
