// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TaskOnSuccessApplyConfiguration represents a declarative configuration of the TaskOnSuccess type for use
// with apply.
//
// TaskOnSuccess lists what Kwerft does once the Task succeeds.
type TaskOnSuccessApplyConfiguration struct {
	// Restart rolls out these Apps in the same project, e.g. a server that has
	// to reopen a file the job replaced. Kwerft does it, not the job, so the
	// job needs no permissions of its own.
	Restart []string `json:"restart,omitempty"`
}

// TaskOnSuccessApplyConfiguration constructs a declarative configuration of the TaskOnSuccess type for use with
// apply.
func TaskOnSuccess() *TaskOnSuccessApplyConfiguration {
	return &TaskOnSuccessApplyConfiguration{}
}

// WithRestart adds the given value to the Restart field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Restart field.
func (b *TaskOnSuccessApplyConfiguration) WithRestart(values ...string) *TaskOnSuccessApplyConfiguration {
	for i := range values {
		b.Restart = append(b.Restart, values[i])
	}
	return b
}
