// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TaskSpecApplyConfiguration represents a declarative configuration of the TaskSpec type for use
// with apply.
//
// TaskSpec is one run of a container to completion. It has the shape of an
// App (source, command, env, volumes, resources, egress) minus ports,
// replicas and health checks.
//
// With FromApp the Task starts from that App: its image (also the built image
// of a Git App), command, env, size/resources, egress and shared Volumes.
// Fields set on the Task win: source, command, size/resources and egress
// replace the App's; env and volumes are merged by name and path. The App is
// read once, when the Task starts; later changes to it do not affect the run.
//
// Env applies in this order, later wins: the App's env, Env, EnvOverrides.
// EnvOverrides holds the per-run changes of "run now" (FORCE=1, DRY_RUN=1),
// kept apart from Env so a run shows what was different about it.
type TaskSpecApplyConfiguration struct {
	// FromApp names an App in the same project to inherit from.
	FromApp *string                      `json:"fromApp,omitempty"`
	Source  *AppSourceApplyConfiguration `json:"source,omitempty"`
	// Size is a preset for requests and limits; custom uses Resources.
	// Empty means the App's size with FromApp, else small.
	Size      *string                  `json:"size,omitempty"`
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// Command replaces the image's entrypoint, one argument per item:
	// ["sh", "-c", "echo hi"], not ["sh -c echo hi"].
	Command []string    `json:"command,omitempty"`
	Env     []v1.EnvVar `json:"env,omitempty"`
	// EnvOverrides is applied last; set by "run now".
	EnvOverrides []v1.EnvVar `json:"envOverrides,omitempty"`
	// Egress controls outbound traffic to the internet. Empty means the
	// App's egress with FromApp, else https.
	Egress *string `json:"egress,omitempty"`
	// Volumes mounts shared Volumes and Secrets. A Task has no disk of its
	// own.
	Volumes []AppVolumeApplyConfiguration `json:"volumes,omitempty"`
	// Timeout stops the run (all retries together) after this long, e.g. 30m.
	Timeout *metav1.Duration `json:"timeout,omitempty"`
	// StopSeconds is how long a run gets to finish after it is told to stop
	// (the Task deleted, its timeout reached, the node drained): the time
	// between SIGTERM and SIGKILL. Default 30. A job that saves its progress
	// on SIGTERM, such as a long import or a reseed finishing the work in
	// hand, needs more.
	StopSeconds *int32 `json:"stopSeconds,omitempty"`
	// Retries is how often a failed run is started again.
	Retries *int32 `json:"retries,omitempty"`
	// TTLSecondsAfterFinished is how long a finished run (its pod and logs)
	// is kept. Default 7 days.
	TTLSecondsAfterFinished *int32                           `json:"ttlSecondsAfterFinished,omitempty"`
	OnSuccess               *TaskOnSuccessApplyConfiguration `json:"onSuccess,omitempty"`
}

// TaskSpecApplyConfiguration constructs a declarative configuration of the TaskSpec type for use with
// apply.
func TaskSpec() *TaskSpecApplyConfiguration {
	return &TaskSpecApplyConfiguration{}
}

// WithFromApp sets the FromApp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FromApp field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithFromApp(value string) *TaskSpecApplyConfiguration {
	b.FromApp = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithSource(value *AppSourceApplyConfiguration) *TaskSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithSize(value string) *TaskSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *TaskSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *TaskSpecApplyConfiguration) WithCommand(values ...string) *TaskSpecApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *TaskSpecApplyConfiguration) WithEnv(values ...v1.EnvVar) *TaskSpecApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithEnvOverrides adds the given value to the EnvOverrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EnvOverrides field.
func (b *TaskSpecApplyConfiguration) WithEnvOverrides(values ...v1.EnvVar) *TaskSpecApplyConfiguration {
	for i := range values {
		b.EnvOverrides = append(b.EnvOverrides, values[i])
	}
	return b
}

// WithEgress sets the Egress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Egress field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithEgress(value string) *TaskSpecApplyConfiguration {
	b.Egress = &value
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *TaskSpecApplyConfiguration) WithVolumes(values ...*AppVolumeApplyConfiguration) *TaskSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.Volumes = append(b.Volumes, *values[i])
	}
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithTimeout(value metav1.Duration) *TaskSpecApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithStopSeconds sets the StopSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StopSeconds field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithStopSeconds(value int32) *TaskSpecApplyConfiguration {
	b.StopSeconds = &value
	return b
}

// WithRetries sets the Retries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retries field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithRetries(value int32) *TaskSpecApplyConfiguration {
	b.Retries = &value
	return b
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithTTLSecondsAfterFinished(value int32) *TaskSpecApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}

// WithOnSuccess sets the OnSuccess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnSuccess field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithOnSuccess(value *TaskOnSuccessApplyConfiguration) *TaskSpecApplyConfiguration {
	b.OnSuccess = value
	return b
}
