// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TrafficPeerApplyConfiguration represents a declarative configuration of the TrafficPeer type for use
// with apply.
//
// TrafficPeer is one side of a TrafficRule. Exactly one field is set.
type TrafficPeerApplyConfiguration struct {
	// App in this rule's project, or "<project>/<app>" in another.
	App *string `json:"app,omitempty"`
	// Project: every app of that project.
	Project *string `json:"project,omitempty"`
	// Internet: traffic from outside the cluster through the ingress
	// (sources), or to public addresses (destinations).
	Internet *bool `json:"internet,omitempty"`
	// CIDR outside the cluster, e.g. 10.0.0.0/16 (a Hetzner private network).
	CIDR *string `json:"cidr,omitempty"`
}

// TrafficPeerApplyConfiguration constructs a declarative configuration of the TrafficPeer type for use with
// apply.
func TrafficPeer() *TrafficPeerApplyConfiguration {
	return &TrafficPeerApplyConfiguration{}
}

// WithApp sets the App field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the App field is set to the value of the last call.
func (b *TrafficPeerApplyConfiguration) WithApp(value string) *TrafficPeerApplyConfiguration {
	b.App = &value
	return b
}

// WithProject sets the Project field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Project field is set to the value of the last call.
func (b *TrafficPeerApplyConfiguration) WithProject(value string) *TrafficPeerApplyConfiguration {
	b.Project = &value
	return b
}

// WithInternet sets the Internet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Internet field is set to the value of the last call.
func (b *TrafficPeerApplyConfiguration) WithInternet(value bool) *TrafficPeerApplyConfiguration {
	b.Internet = &value
	return b
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *TrafficPeerApplyConfiguration) WithCIDR(value string) *TrafficPeerApplyConfiguration {
	b.CIDR = &value
	return b
}
