// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TrafficRuleStatusApplyConfiguration represents a declarative configuration of the TrafficRuleStatus type for use
// with apply.
//
// TrafficRuleStatus is written by the TrafficRule reconciler.
type TrafficRuleStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Policies are the CiliumNetworkPolicies the rule became.
	Policies   []string                         `json:"policies,omitempty"`
	Counts     *TrafficCountsApplyConfiguration `json:"counts,omitempty"`
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// TrafficRuleStatusApplyConfiguration constructs a declarative configuration of the TrafficRuleStatus type for use with
// apply.
func TrafficRuleStatus() *TrafficRuleStatusApplyConfiguration {
	return &TrafficRuleStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *TrafficRuleStatusApplyConfiguration) WithObservedGeneration(value int64) *TrafficRuleStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPolicies adds the given value to the Policies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Policies field.
func (b *TrafficRuleStatusApplyConfiguration) WithPolicies(values ...string) *TrafficRuleStatusApplyConfiguration {
	for i := range values {
		b.Policies = append(b.Policies, values[i])
	}
	return b
}

// WithCounts sets the Counts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Counts field is set to the value of the last call.
func (b *TrafficRuleStatusApplyConfiguration) WithCounts(value *TrafficCountsApplyConfiguration) *TrafficRuleStatusApplyConfiguration {
	b.Counts = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TrafficRuleStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TrafficRuleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
