// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TrafficCountsApplyConfiguration represents a declarative configuration of the TrafficCounts type for use
// with apply.
//
// TrafficCounts are Hubble's flow counts for a rule over the last hour.
type TrafficCountsApplyConfiguration struct {
	Allowed *int64   `json:"allowed,omitempty"`
	Dropped *int64   `json:"dropped,omitempty"`
	Since   *v1.Time `json:"since,omitempty"`
}

// TrafficCountsApplyConfiguration constructs a declarative configuration of the TrafficCounts type for use with
// apply.
func TrafficCounts() *TrafficCountsApplyConfiguration {
	return &TrafficCountsApplyConfiguration{}
}

// WithAllowed sets the Allowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allowed field is set to the value of the last call.
func (b *TrafficCountsApplyConfiguration) WithAllowed(value int64) *TrafficCountsApplyConfiguration {
	b.Allowed = &value
	return b
}

// WithDropped sets the Dropped field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dropped field is set to the value of the last call.
func (b *TrafficCountsApplyConfiguration) WithDropped(value int64) *TrafficCountsApplyConfiguration {
	b.Dropped = &value
	return b
}

// WithSince sets the Since field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Since field is set to the value of the last call.
func (b *TrafficCountsApplyConfiguration) WithSince(value v1.Time) *TrafficCountsApplyConfiguration {
	b.Since = &value
	return b
}
