// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TrafficRuleSpecApplyConfiguration represents a declarative configuration of the TrafficRuleSpec type for use
// with apply.
//
// TrafficRuleSpec allows traffic between apps, projects and the outside, on
// top of the project's default (isolated projects deny all ingress from
// other projects; Apps open their own ports to the ingress and their
// project).
type TrafficRuleSpecApplyConfiguration struct {
	// From are the sources. For an ingress rule (To empty or apps of this
	// project) they may be anything; Internet means through the ingress.
	From []TrafficPeerApplyConfiguration `json:"from,omitempty"`
	// To are the destinations. Apps of this rule's project receive (ingress);
	// Internet, CIDR or other projects' apps are reached by From, which
	// must then be apps of this project (egress).
	To []TrafficPeerApplyConfiguration `json:"to,omitempty"`
	// Ports; empty means every port.
	Ports       []TrafficPortApplyConfiguration `json:"ports,omitempty"`
	Description *string                         `json:"description,omitempty"`
	// Disabled rules are kept but not applied.
	Disabled *bool `json:"disabled,omitempty"`
}

// TrafficRuleSpecApplyConfiguration constructs a declarative configuration of the TrafficRuleSpec type for use with
// apply.
func TrafficRuleSpec() *TrafficRuleSpecApplyConfiguration {
	return &TrafficRuleSpecApplyConfiguration{}
}

// WithFrom adds the given value to the From field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the From field.
func (b *TrafficRuleSpecApplyConfiguration) WithFrom(values ...*TrafficPeerApplyConfiguration) *TrafficRuleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFrom")
		}
		b.From = append(b.From, *values[i])
	}
	return b
}

// WithTo adds the given value to the To field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the To field.
func (b *TrafficRuleSpecApplyConfiguration) WithTo(values ...*TrafficPeerApplyConfiguration) *TrafficRuleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTo")
		}
		b.To = append(b.To, *values[i])
	}
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *TrafficRuleSpecApplyConfiguration) WithPorts(values ...*TrafficPortApplyConfiguration) *TrafficRuleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPorts")
		}
		b.Ports = append(b.Ports, *values[i])
	}
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *TrafficRuleSpecApplyConfiguration) WithDescription(value string) *TrafficRuleSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithDisabled sets the Disabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disabled field is set to the value of the last call.
func (b *TrafficRuleSpecApplyConfiguration) WithDisabled(value bool) *TrafficRuleSpecApplyConfiguration {
	b.Disabled = &value
	return b
}
