// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TrafficPortApplyConfiguration represents a declarative configuration of the TrafficPort type for use
// with apply.
//
// TrafficPort is a port and protocol a rule allows.
type TrafficPortApplyConfiguration struct {
	Port     *int32  `json:"port,omitempty"`
	EndPort  *int32  `json:"endPort,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
}

// TrafficPortApplyConfiguration constructs a declarative configuration of the TrafficPort type for use with
// apply.
func TrafficPort() *TrafficPortApplyConfiguration {
	return &TrafficPortApplyConfiguration{}
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *TrafficPortApplyConfiguration) WithPort(value int32) *TrafficPortApplyConfiguration {
	b.Port = &value
	return b
}

// WithEndPort sets the EndPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndPort field is set to the value of the last call.
func (b *TrafficPortApplyConfiguration) WithEndPort(value int32) *TrafficPortApplyConfiguration {
	b.EndPort = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *TrafficPortApplyConfiguration) WithProtocol(value string) *TrafficPortApplyConfiguration {
	b.Protocol = &value
	return b
}
