// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// UpdateSettingsApplyConfiguration represents a declarative configuration of the UpdateSettings type for use
// with apply.
//
// UpdateSettings: channel, policy and the maintenance window for AutoPatch.
type UpdateSettingsApplyConfiguration struct {
	Channel *string                   `json:"channel,omitempty"`
	Policy  *apiv1alpha1.UpdatePolicy `json:"policy,omitempty"`
	// KubernetesPatches lets AutoPatch install k3s patch versions too.
	KubernetesPatches *bool                                `json:"kubernetesPatches,omitempty"`
	Window            *MaintenanceWindowApplyConfiguration `json:"window,omitempty"`
}

// UpdateSettingsApplyConfiguration constructs a declarative configuration of the UpdateSettings type for use with
// apply.
func UpdateSettings() *UpdateSettingsApplyConfiguration {
	return &UpdateSettingsApplyConfiguration{}
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *UpdateSettingsApplyConfiguration) WithChannel(value string) *UpdateSettingsApplyConfiguration {
	b.Channel = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *UpdateSettingsApplyConfiguration) WithPolicy(value apiv1alpha1.UpdatePolicy) *UpdateSettingsApplyConfiguration {
	b.Policy = &value
	return b
}

// WithKubernetesPatches sets the KubernetesPatches field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubernetesPatches field is set to the value of the last call.
func (b *UpdateSettingsApplyConfiguration) WithKubernetesPatches(value bool) *UpdateSettingsApplyConfiguration {
	b.KubernetesPatches = &value
	return b
}

// WithWindow sets the Window field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Window field is set to the value of the last call.
func (b *UpdateSettingsApplyConfiguration) WithWindow(value *MaintenanceWindowApplyConfiguration) *UpdateSettingsApplyConfiguration {
	b.Window = value
	return b
}
