// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// UpdatesStatusApplyConfiguration represents a declarative configuration of the UpdatesStatus type for use
// with apply.
//
// UpdatesStatus is the last release discovery.
type UpdatesStatusApplyConfiguration struct {
	CheckedAt *v1.Time                            `json:"checkedAt,omitempty"`
	Current   *UpgradeVersionsApplyConfiguration  `json:"current,omitempty"`
	Available []AvailableUpdateApplyConfiguration `json:"available,omitempty"`
	Error     *string                             `json:"error,omitempty"`
	// AutoPatchPausedBy names the auto-update that failed or rolled back;
	// AutoPatch waits until an owner resumes it.
	AutoPatchPausedBy *string `json:"autoPatchPausedBy,omitempty"`
}

// UpdatesStatusApplyConfiguration constructs a declarative configuration of the UpdatesStatus type for use with
// apply.
func UpdatesStatus() *UpdatesStatusApplyConfiguration {
	return &UpdatesStatusApplyConfiguration{}
}

// WithCheckedAt sets the CheckedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CheckedAt field is set to the value of the last call.
func (b *UpdatesStatusApplyConfiguration) WithCheckedAt(value v1.Time) *UpdatesStatusApplyConfiguration {
	b.CheckedAt = &value
	return b
}

// WithCurrent sets the Current field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Current field is set to the value of the last call.
func (b *UpdatesStatusApplyConfiguration) WithCurrent(value *UpgradeVersionsApplyConfiguration) *UpdatesStatusApplyConfiguration {
	b.Current = value
	return b
}

// WithAvailable adds the given value to the Available field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Available field.
func (b *UpdatesStatusApplyConfiguration) WithAvailable(values ...*AvailableUpdateApplyConfiguration) *UpdatesStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAvailable")
		}
		b.Available = append(b.Available, *values[i])
	}
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *UpdatesStatusApplyConfiguration) WithError(value string) *UpdatesStatusApplyConfiguration {
	b.Error = &value
	return b
}

// WithAutoPatchPausedBy sets the AutoPatchPausedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoPatchPausedBy field is set to the value of the last call.
func (b *UpdatesStatusApplyConfiguration) WithAutoPatchPausedBy(value string) *UpdatesStatusApplyConfiguration {
	b.AutoPatchPausedBy = &value
	return b
}
