// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// UpgradeStatusApplyConfiguration represents a declarative configuration of the UpgradeStatus type for use
// with apply.
//
// UpgradeStatus is written by the Upgrade controller and the runner.
type UpgradeStatusApplyConfiguration struct {
	ObservedGeneration *int64                             `json:"observedGeneration,omitempty"`
	Phase              *apiv1alpha1.UpgradePhase          `json:"phase,omitempty"`
	From               *UpgradeVersionsApplyConfiguration `json:"from,omitempty"`
	Preflight          []UpgradeCheckApplyConfiguration   `json:"preflight,omitempty"`
	Backup             *UpgradeBackupApplyConfiguration   `json:"backup,omitempty"`
	Steps              []UpgradeStepApplyConfiguration    `json:"steps,omitempty"`
	Nodes              []UpgradeNodeApplyConfiguration    `json:"nodes,omitempty"`
	// Reason of a failure: Usage, Preflight, Network, Kubernetes, Platform,
	// Kwerft (the installer's exit codes), Verify or Timeout.
	Reason     *string                              `json:"reason,omitempty"`
	Message    *string                              `json:"message,omitempty"`
	StartedAt  *v1.Time                             `json:"startedAt,omitempty"`
	FinishedAt *v1.Time                             `json:"finishedAt,omitempty"`
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// UpgradeStatusApplyConfiguration constructs a declarative configuration of the UpgradeStatus type for use with
// apply.
func UpgradeStatus() *UpgradeStatusApplyConfiguration {
	return &UpgradeStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithObservedGeneration(value int64) *UpgradeStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithPhase(value apiv1alpha1.UpgradePhase) *UpgradeStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithFrom(value *UpgradeVersionsApplyConfiguration) *UpgradeStatusApplyConfiguration {
	b.From = value
	return b
}

// WithPreflight adds the given value to the Preflight field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Preflight field.
func (b *UpgradeStatusApplyConfiguration) WithPreflight(values ...*UpgradeCheckApplyConfiguration) *UpgradeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPreflight")
		}
		b.Preflight = append(b.Preflight, *values[i])
	}
	return b
}

// WithBackup sets the Backup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backup field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithBackup(value *UpgradeBackupApplyConfiguration) *UpgradeStatusApplyConfiguration {
	b.Backup = value
	return b
}

// WithSteps adds the given value to the Steps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Steps field.
func (b *UpgradeStatusApplyConfiguration) WithSteps(values ...*UpgradeStepApplyConfiguration) *UpgradeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSteps")
		}
		b.Steps = append(b.Steps, *values[i])
	}
	return b
}

// WithNodes adds the given value to the Nodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodes field.
func (b *UpgradeStatusApplyConfiguration) WithNodes(values ...*UpgradeNodeApplyConfiguration) *UpgradeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNodes")
		}
		b.Nodes = append(b.Nodes, *values[i])
	}
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithReason(value string) *UpgradeStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithMessage(value string) *UpgradeStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithStartedAt(value v1.Time) *UpgradeStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithFinishedAt sets the FinishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FinishedAt field is set to the value of the last call.
func (b *UpgradeStatusApplyConfiguration) WithFinishedAt(value v1.Time) *UpgradeStatusApplyConfiguration {
	b.FinishedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *UpgradeStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *UpgradeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
