// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
)

// UpgradeSpecApplyConfiguration represents a declarative configuration of the UpgradeSpec type for use
// with apply.
//
// UpgradeSpec is one attempt to move Kwerft or k3s to a version. The API
// creates it as the owner who asked (annotation kwerft.dev/requested-by);
// the update policy creates AutoPatch ones as "auto-update".
type UpgradeSpecApplyConfiguration struct {
	Component *apiv1alpha1.UpgradeComponent `json:"component,omitempty"`
	// Version is a Kwerft release (0.6.0) or a k3s version (v1.38.1+k3s1).
	Version *string `json:"version,omitempty"`
	// AcceptDataRollback acknowledges that rolling back a release marked
	// rollbackSafe: false restores the database copy, losing writes made
	// since the backup.
	AcceptDataRollback *bool `json:"acceptDataRollback,omitempty"`
}

// UpgradeSpecApplyConfiguration constructs a declarative configuration of the UpgradeSpec type for use with
// apply.
func UpgradeSpec() *UpgradeSpecApplyConfiguration {
	return &UpgradeSpecApplyConfiguration{}
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *UpgradeSpecApplyConfiguration) WithComponent(value apiv1alpha1.UpgradeComponent) *UpgradeSpecApplyConfiguration {
	b.Component = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *UpgradeSpecApplyConfiguration) WithVersion(value string) *UpgradeSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithAcceptDataRollback sets the AcceptDataRollback field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcceptDataRollback field is set to the value of the last call.
func (b *UpgradeSpecApplyConfiguration) WithAcceptDataRollback(value bool) *UpgradeSpecApplyConfiguration {
	b.AcceptDataRollback = &value
	return b
}
