// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// UpgradeCheckApplyConfiguration represents a declarative configuration of the UpgradeCheck type for use
// with apply.
//
// UpgradeCheck is one preflight check.
type UpgradeCheckApplyConfiguration struct {
	Check   *string `json:"check,omitempty"`
	OK      *bool   `json:"ok,omitempty"`
	Message *string `json:"message,omitempty"`
	// Warning: a failed check that does not block (e.g. deprecated APIs on
	// a patch upgrade).
	Warning *bool `json:"warning,omitempty"`
}

// UpgradeCheckApplyConfiguration constructs a declarative configuration of the UpgradeCheck type for use with
// apply.
func UpgradeCheck() *UpgradeCheckApplyConfiguration {
	return &UpgradeCheckApplyConfiguration{}
}

// WithCheck sets the Check field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Check field is set to the value of the last call.
func (b *UpgradeCheckApplyConfiguration) WithCheck(value string) *UpgradeCheckApplyConfiguration {
	b.Check = &value
	return b
}

// WithOK sets the OK field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OK field is set to the value of the last call.
func (b *UpgradeCheckApplyConfiguration) WithOK(value bool) *UpgradeCheckApplyConfiguration {
	b.OK = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *UpgradeCheckApplyConfiguration) WithMessage(value string) *UpgradeCheckApplyConfiguration {
	b.Message = &value
	return b
}

// WithWarning sets the Warning field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Warning field is set to the value of the last call.
func (b *UpgradeCheckApplyConfiguration) WithWarning(value bool) *UpgradeCheckApplyConfiguration {
	b.Warning = &value
	return b
}
