// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// UpgradeNodeApplyConfiguration represents a declarative configuration of the UpgradeNode type for use
// with apply.
//
// UpgradeNode is one node's progress in a Kubernetes upgrade.
type UpgradeNodeApplyConfiguration struct {
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
	// State: Waiting, Draining, Upgrading, Done or Failed.
	State   *string `json:"state,omitempty"`
	Message *string `json:"message,omitempty"`
}

// UpgradeNodeApplyConfiguration constructs a declarative configuration of the UpgradeNode type for use with
// apply.
func UpgradeNode() *UpgradeNodeApplyConfiguration {
	return &UpgradeNodeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *UpgradeNodeApplyConfiguration) WithName(value string) *UpgradeNodeApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *UpgradeNodeApplyConfiguration) WithVersion(value string) *UpgradeNodeApplyConfiguration {
	b.Version = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *UpgradeNodeApplyConfiguration) WithState(value string) *UpgradeNodeApplyConfiguration {
	b.State = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *UpgradeNodeApplyConfiguration) WithMessage(value string) *UpgradeNodeApplyConfiguration {
	b.Message = &value
	return b
}
