// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// UpgradeVersionsApplyConfiguration represents a declarative configuration of the UpgradeVersions type for use
// with apply.
//
// UpgradeVersions are the running versions before an Upgrade.
type UpgradeVersionsApplyConfiguration struct {
	Kwerft     *string `json:"kwerft,omitempty"`
	Kubernetes *string `json:"kubernetes,omitempty"`
}

// UpgradeVersionsApplyConfiguration constructs a declarative configuration of the UpgradeVersions type for use with
// apply.
func UpgradeVersions() *UpgradeVersionsApplyConfiguration {
	return &UpgradeVersionsApplyConfiguration{}
}

// WithKwerft sets the Kwerft field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kwerft field is set to the value of the last call.
func (b *UpgradeVersionsApplyConfiguration) WithKwerft(value string) *UpgradeVersionsApplyConfiguration {
	b.Kwerft = &value
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *UpgradeVersionsApplyConfiguration) WithKubernetes(value string) *UpgradeVersionsApplyConfiguration {
	b.Kubernetes = &value
	return b
}
