// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// UpgradeStepApplyConfiguration represents a declarative configuration of the UpgradeStep type for use
// with apply.
//
// UpgradeStep is one installer stage, with its summary line as printed.
type UpgradeStepApplyConfiguration struct {
	ID    *string `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
	// State: Running, Done, Skipped or Failed.
	State  *string  `json:"state,omitempty"`
	Detail *string  `json:"detail,omitempty"`
	At     *v1.Time `json:"at,omitempty"`
}

// UpgradeStepApplyConfiguration constructs a declarative configuration of the UpgradeStep type for use with
// apply.
func UpgradeStep() *UpgradeStepApplyConfiguration {
	return &UpgradeStepApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *UpgradeStepApplyConfiguration) WithID(value string) *UpgradeStepApplyConfiguration {
	b.ID = &value
	return b
}

// WithLabel sets the Label field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Label field is set to the value of the last call.
func (b *UpgradeStepApplyConfiguration) WithLabel(value string) *UpgradeStepApplyConfiguration {
	b.Label = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *UpgradeStepApplyConfiguration) WithState(value string) *UpgradeStepApplyConfiguration {
	b.State = &value
	return b
}

// WithDetail sets the Detail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Detail field is set to the value of the last call.
func (b *UpgradeStepApplyConfiguration) WithDetail(value string) *UpgradeStepApplyConfiguration {
	b.Detail = &value
	return b
}

// WithAt sets the At field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the At field is set to the value of the last call.
func (b *UpgradeStepApplyConfiguration) WithAt(value v1.Time) *UpgradeStepApplyConfiguration {
	b.At = &value
	return b
}
