// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// UpgradeBackupApplyConfiguration represents a declarative configuration of the UpgradeBackup type for use
// with apply.
//
// UpgradeBackup is what the upgrade can roll back to.
type UpgradeBackupApplyConfiguration struct {
	EtcdSnapshot *string `json:"etcdSnapshot,omitempty"`
	// Database is the path of the SQLite copy in the console's volume.
	Database *string `json:"database,omitempty"`
	// HelmRevisions maps "<namespace>/<release>" to its revision before the
	// upgrade.
	HelmRevisions map[string]int32 `json:"helmRevisions,omitempty"`
}

// UpgradeBackupApplyConfiguration constructs a declarative configuration of the UpgradeBackup type for use with
// apply.
func UpgradeBackup() *UpgradeBackupApplyConfiguration {
	return &UpgradeBackupApplyConfiguration{}
}

// WithEtcdSnapshot sets the EtcdSnapshot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EtcdSnapshot field is set to the value of the last call.
func (b *UpgradeBackupApplyConfiguration) WithEtcdSnapshot(value string) *UpgradeBackupApplyConfiguration {
	b.EtcdSnapshot = &value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *UpgradeBackupApplyConfiguration) WithDatabase(value string) *UpgradeBackupApplyConfiguration {
	b.Database = &value
	return b
}

// WithHelmRevisions puts the entries into the HelmRevisions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the HelmRevisions field,
// overwriting an existing map entries in HelmRevisions field with the same key.
func (b *UpgradeBackupApplyConfiguration) WithHelmRevisions(entries map[string]int32) *UpgradeBackupApplyConfiguration {
	if b.HelmRevisions == nil && len(entries) > 0 {
		b.HelmRevisions = make(map[string]int32, len(entries))
	}
	for k, v := range entries {
		b.HelmRevisions[k] = v
	}
	return b
}
