// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// VolumeStatusApplyConfiguration represents a declarative configuration of the VolumeStatus type for use
// with apply.
//
// VolumeStatus is written by the Volume reconciler.
type VolumeStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Phase of the claim: Pending (local-nvme binds when the first pod
	// mounts it), Bound or Lost.
	Phase *v1.PersistentVolumeClaimPhase `json:"phase,omitempty"`
	// Capacity actually provisioned; can be larger than spec.size.
	Capacity *resource.Quantity `json:"capacity,omitempty"`
	// ClaimName is the PersistentVolumeClaim behind this Volume.
	ClaimName *string `json:"claimName,omitempty"`
	// UsedBy lists the Apps, Schedules and unfinished Tasks that mount this
	// Volume, as "App/api" or "Task/import-1". While it is not empty, deleting
	// the Volume waits (the volume-protection finalizer).
	UsedBy     []string                             `json:"usedBy,omitempty"`
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// VolumeStatusApplyConfiguration constructs a declarative configuration of the VolumeStatus type for use with
// apply.
func VolumeStatus() *VolumeStatusApplyConfiguration {
	return &VolumeStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithObservedGeneration(value int64) *VolumeStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithPhase(value v1.PersistentVolumeClaimPhase) *VolumeStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithCapacity(value resource.Quantity) *VolumeStatusApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithClaimName sets the ClaimName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimName field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithClaimName(value string) *VolumeStatusApplyConfiguration {
	b.ClaimName = &value
	return b
}

// WithUsedBy adds the given value to the UsedBy field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UsedBy field.
func (b *VolumeStatusApplyConfiguration) WithUsedBy(values ...string) *VolumeStatusApplyConfiguration {
	for i := range values {
		b.UsedBy = append(b.UsedBy, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VolumeStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *VolumeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
