// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// VolumeSpecApplyConfiguration represents a declarative configuration of the VolumeSpec type for use
// with apply.
//
// VolumeSpec is a disk that Apps and Tasks in the same project mount by name
// (AppVolume.volume), e.g. a job writes a file that a server then reads.
//
// The disk is ReadWriteOnce: every pod that mounts it runs on the same node.
// local-nvme volumes are pinned to the node they were created on; for
// hcloud-volume, pods that share a Volume prefer the node it is attached to.
type VolumeSpecApplyConfiguration struct {
	// Size of the disk. Growing it works for hcloud-volume; local-nvme
	// volumes cannot be resized.
	Size *resource.Quantity `json:"size,omitempty"`
	// Class is local-nvme (fastest, pinned to one node) or hcloud-volume
	// (movable between Hetzner Cloud nodes).
	Class *string `json:"class,omitempty"`
}

// VolumeSpecApplyConfiguration constructs a declarative configuration of the VolumeSpec type for use with
// apply.
func VolumeSpec() *VolumeSpecApplyConfiguration {
	return &VolumeSpecApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithSize(value resource.Quantity) *VolumeSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithClass sets the Class field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Class field is set to the value of the last call.
func (b *VolumeSpecApplyConfiguration) WithClass(value string) *VolumeSpecApplyConfiguration {
	b.Class = &value
	return b
}
