// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/applyconfiguration/api/v1alpha1"
	internal "github.com/ehilzinger/kwerft/api/applyconfiguration/internal"
	v1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=kwerft.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AppSource"):
		return &apiv1alpha1.AppSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AppVolume"):
		return &apiv1alpha1.AppVolumeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CertificateState"):
		return &apiv1alpha1.CertificateStateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleSettings"):
		return &apiv1alpha1.ConsoleSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleSettingsSpec"):
		return &apiv1alpha1.ConsoleSettingsSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleSettingsStatus"):
		return &apiv1alpha1.ConsoleSettingsStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSRecordStatus"):
		return &apiv1alpha1.DNSRecordStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSSettings"):
		return &apiv1alpha1.DNSSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSStatus"):
		return &apiv1alpha1.DNSStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Domain"):
		return &apiv1alpha1.DomainApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DomainSpec"):
		return &apiv1alpha1.DomainSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DomainStatus"):
		return &apiv1alpha1.DomainStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitConnection"):
		return &apiv1alpha1.GitConnectionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitConnectionSpec"):
		return &apiv1alpha1.GitConnectionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitConnectionStatus"):
		return &apiv1alpha1.GitConnectionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitHubAppSettings"):
		return &apiv1alpha1.GitHubAppSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitSource"):
		return &apiv1alpha1.GitSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ImageSource"):
		return &apiv1alpha1.ImageSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Project"):
		return &apiv1alpha1.ProjectApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectSpec"):
		return &apiv1alpha1.ProjectSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectStatus"):
		return &apiv1alpha1.ProjectStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Schedule"):
		return &apiv1alpha1.ScheduleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScheduleHistory"):
		return &apiv1alpha1.ScheduleHistoryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScheduleSpec"):
		return &apiv1alpha1.ScheduleSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScheduleStatus"):
		return &apiv1alpha1.ScheduleStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TaskOnSuccess"):
		return &apiv1alpha1.TaskOnSuccessApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TaskSpec"):
		return &apiv1alpha1.TaskSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Volume"):
		return &apiv1alpha1.VolumeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VolumeSpec"):
		return &apiv1alpha1.VolumeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VolumeStatus"):
		return &apiv1alpha1.VolumeStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
