// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/applyconfiguration/api/v1alpha1"
	internal "github.com/ehilzinger/kwerft/api/applyconfiguration/internal"
	v1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=kwerft.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AlertRule"):
		return &apiv1alpha1.AlertRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AlertRuleSpec"):
		return &apiv1alpha1.AlertRuleSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AlertRuleStatus"):
		return &apiv1alpha1.AlertRuleStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AlertScope"):
		return &apiv1alpha1.AlertScopeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AppSource"):
		return &apiv1alpha1.AppSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AppVolume"):
		return &apiv1alpha1.AppVolumeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CertificateState"):
		return &apiv1alpha1.CertificateStateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Cluster"):
		return &apiv1alpha1.ClusterApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterSpec"):
		return &apiv1alpha1.ClusterSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterStatus"):
		return &apiv1alpha1.ClusterStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleSettings"):
		return &apiv1alpha1.ConsoleSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleSettingsSpec"):
		return &apiv1alpha1.ConsoleSettingsSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConsoleSettingsStatus"):
		return &apiv1alpha1.ConsoleSettingsStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSRecordStatus"):
		return &apiv1alpha1.DNSRecordStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSSettings"):
		return &apiv1alpha1.DNSSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DNSStatus"):
		return &apiv1alpha1.DNSStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Domain"):
		return &apiv1alpha1.DomainApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DomainSpec"):
		return &apiv1alpha1.DomainSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DomainStatus"):
		return &apiv1alpha1.DomainStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("EmailSettings"):
		return &apiv1alpha1.EmailSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FirewallRule"):
		return &apiv1alpha1.FirewallRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FirewallRuleSpec"):
		return &apiv1alpha1.FirewallRuleSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FirewallRuleStatus"):
		return &apiv1alpha1.FirewallRuleStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitConnection"):
		return &apiv1alpha1.GitConnectionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitConnectionSpec"):
		return &apiv1alpha1.GitConnectionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitConnectionStatus"):
		return &apiv1alpha1.GitConnectionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitHubAppSettings"):
		return &apiv1alpha1.GitHubAppSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitSource"):
		return &apiv1alpha1.GitSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GitWebhookStatus"):
		return &apiv1alpha1.GitWebhookStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HetznerClusterSpec"):
		return &apiv1alpha1.HetznerClusterSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ImageSource"):
		return &apiv1alpha1.ImageSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodePool"):
		return &apiv1alpha1.NodePoolApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodePoolSpec"):
		return &apiv1alpha1.NodePoolSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodePoolStatus"):
		return &apiv1alpha1.NodePoolStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NotificationChannel"):
		return &apiv1alpha1.NotificationChannelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NotificationChannelSpec"):
		return &apiv1alpha1.NotificationChannelSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NotificationChannelStatus"):
		return &apiv1alpha1.NotificationChannelStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NtfySettings"):
		return &apiv1alpha1.NtfySettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PoolNode"):
		return &apiv1alpha1.PoolNodeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Project"):
		return &apiv1alpha1.ProjectApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectMember"):
		return &apiv1alpha1.ProjectMemberApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectSpec"):
		return &apiv1alpha1.ProjectSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectStatus"):
		return &apiv1alpha1.ProjectStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Schedule"):
		return &apiv1alpha1.ScheduleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScheduleHistory"):
		return &apiv1alpha1.ScheduleHistoryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScheduleSpec"):
		return &apiv1alpha1.ScheduleSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ScheduleStatus"):
		return &apiv1alpha1.ScheduleStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SlackSettings"):
		return &apiv1alpha1.SlackSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SSOSettings"):
		return &apiv1alpha1.SSOSettingsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TaskOnSuccess"):
		return &apiv1alpha1.TaskOnSuccessApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TaskSpec"):
		return &apiv1alpha1.TaskSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TrafficCounts"):
		return &apiv1alpha1.TrafficCountsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TrafficPeer"):
		return &apiv1alpha1.TrafficPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TrafficPort"):
		return &apiv1alpha1.TrafficPortApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TrafficRule"):
		return &apiv1alpha1.TrafficRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TrafficRuleSpec"):
		return &apiv1alpha1.TrafficRuleSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TrafficRuleStatus"):
		return &apiv1alpha1.TrafficRuleStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Volume"):
		return &apiv1alpha1.VolumeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VolumeSpec"):
		return &apiv1alpha1.VolumeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VolumeStatus"):
		return &apiv1alpha1.VolumeStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
