// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	apiv1alpha1 "github.com/ehilzinger/kwerft/api/applyconfiguration/api/v1alpha1"
	internal "github.com/ehilzinger/kwerft/api/applyconfiguration/internal"
	v1alpha1 "github.com/ehilzinger/kwerft/api/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=kwerft.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Domain"):
		return &apiv1alpha1.DomainApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DomainSpec"):
		return &apiv1alpha1.DomainSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DomainStatus"):
		return &apiv1alpha1.DomainStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Project"):
		return &apiv1alpha1.ProjectApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectSpec"):
		return &apiv1alpha1.ProjectSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProjectStatus"):
		return &apiv1alpha1.ProjectStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
