// SPDX-FileCopyrightText: 2026 Enzo Hilzinger
// SPDX-License-Identifier: AGPL-3.0-only

import { describe, expect, it } from "vitest";
import {
  derivedOf, derivedText, describeKey, envPlan, envRowsOf, keyList, keyProblem, lastUpdate, missingKeys, parseUser, setNameProblem, sourceOf, withSource,
  type EnvRow,
} from "./secrets";
import type { EnvVar } from "./workloads";

const ref = (name: string, key: string) => ({ secretKeyRef: { name, key } });

const spec: EnvVar[] = [
  { name: "LOG_LEVEL", value: "info" },
  { name: "SESSION_SECRET", valueFrom: ref("api-env", "SESSION_SECRET") },
  { name: "STRIPE_KEY", valueFrom: ref("payments", "STRIPE_KEY") },
  { name: "POD_IP", valueFrom: { fieldRef: { fieldPath: "status.podIP" } } },
];

describe("the env editor", () => {
  it("reads plain values, the app's own keys, shared keys and other references", () => {
    expect(envRowsOf(spec, "api").map((r) => [r.name, r.kind, r.key ?? r.value])).toEqual([
      ["LOG_LEVEL", "plain", "info"],
      ["SESSION_SECRET", "own", "SESSION_SECRET"],
      ["STRIPE_KEY", "ref", "STRIPE_KEY"],
      ["POD_IP", "other", ""],
    ]);
  });

  it("round-trips an unchanged environment without writing a value", () => {
    const plan = envPlan(envRowsOf(spec, "api"), "api", spec);
    expect(plan.env).toEqual(spec);
    expect(plan.put).toEqual([]);
    expect(plan.remove).toEqual([]);
    expect(plan.error).toBeUndefined();
  });

  it("moves a plain value into the app's own set when marked secret", () => {
    const rows = envRowsOf(spec, "api");
    rows[0] = withSource(rows[0]!, "own");
    const plan = envPlan(rows, "api", spec);
    expect(plan.put).toEqual([{ key: "LOG_LEVEL", value: "info" }]);
    expect(plan.env[0]).toEqual({ name: "LOG_LEVEL", valueFrom: ref("api-env", "LOG_LEVEL") });
    // The value is nowhere in the App spec.
    expect(JSON.stringify(plan.env)).not.toContain("info");
  });

  it("writes a replaced value under the existing key, also after a rename", () => {
    const rows = envRowsOf(spec, "api");
    rows[1] = { ...rows[1]!, name: "COOKIE_SECRET", value: "new" };
    const plan = envPlan(rows, "api", spec);
    expect(plan.put).toEqual([{ key: "SESSION_SECRET", value: "new" }]);
    expect(plan.env[1]).toEqual({ name: "COOKIE_SECRET", valueFrom: ref("api-env", "SESSION_SECRET") });
  });

  it("removes keys of the own set nothing references any more", () => {
    const rows = envRowsOf(spec, "api").filter((r) => r.name !== "SESSION_SECRET");
    expect(envPlan(rows, "api", spec).remove).toEqual(["SESSION_SECRET"]);
    // Turning it plain needs a value and drops the key too.
    const plain = envRowsOf(spec, "api");
    plain[1] = { ...withSource(plain[1]!, "plain"), value: "visible" };
    const plan = envPlan(plain, "api", spec);
    expect(plan.remove).toEqual(["SESSION_SECRET"]);
    expect(plan.env[1]).toEqual({ name: "SESSION_SECRET", value: "visible" });
  });

  it("asks for the value of a new secret variable", () => {
    const rows: EnvRow[] = [{ name: "TOKEN", kind: "own", value: "" }];
    expect(envPlan(rows, "api", []).error).toEqual({ index: 0, message: "Enter the value: it is stored write-only and nobody can read it back." });
    expect(envPlan([{ name: "", kind: "own", value: "x" }], "api", []).error?.index).toBe(0);
  });

  it("picks a key of a shared set", () => {
    const row = withSource({ name: "", kind: "plain", value: "" }, "ref:payments/STRIPE_WEBHOOK");
    expect(row).toEqual({ name: "STRIPE_WEBHOOK", kind: "ref", value: "", set: "payments", key: "STRIPE_WEBHOOK" });
    expect(sourceOf(row)).toBe("ref:payments/STRIPE_WEBHOOK");
    expect(envPlan([row], "api", []).env).toEqual([{ name: "STRIPE_WEBHOOK", valueFrom: ref("payments", "STRIPE_WEBHOOK") }]);
    expect(envPlan([{ name: "X", kind: "ref", value: "" }], "api", []).error?.message).toBe("Choose a key of a secret set.");
  });

  it("skips empty rows", () => {
    expect(envPlan([{ name: "", kind: "plain", value: "" }], "api", []).env).toEqual([]);
  });
});

describe("secret sets", () => {
  const set = {
    keys: [
      { name: "A", updatedAt: "2026-10-05T10:00:00Z", updatedBy: "jonas@example.com", source: "Set" as const },
      { name: "B", updatedAt: "2026-10-05T12:00:00Z", source: "Generated" as const },
      { name: "URL" },
    ],
    missing: ["App/notifier: SMTP_USER", "Task/x: SMTP_USER", "App/api: SMTP_PASSWORD"],
    derived: [{ key: "URL", template: "postgres://app:${B}@db/app" }],
  };

  it("summarises keys", () => {
    expect(lastUpdate(set)?.name).toBe("B");
    expect(missingKeys(set)).toEqual(["SMTP_USER", "SMTP_PASSWORD"]);
    expect(describeKey(set.keys[0]!, set)).toBe("Set by jonas@example.com");
    expect(describeKey(set.keys[1]!, set)).toBe("Generated by Kwerft");
    expect(describeKey(set.keys[2]!, set)).toBe("Derived from ${B}");
    expect(parseUser("Schedule/nightly")).toEqual({ kind: "Schedule", name: "nightly" });
  });

  it("checks names and keys", () => {
    expect(setNameProblem("payments")).toBeUndefined();
    expect(setNameProblem("Payments")).toBeDefined();
    expect(setNameProblem("x".repeat(64))).toBeDefined();
    expect(keyProblem("tls.crt")).toBeUndefined();
    expect(keyProblem("a/b")).toBeDefined();
  });

  it("parses the generated and derived lists", () => {
    expect(keyList("PASSWORD, ADMIN_PASSWORD PASSWORD")).toEqual({ keys: ["PASSWORD", "ADMIN_PASSWORD"], bad: undefined });
    expect(keyList("OK, no/slash").bad).toBe("no/slash");
    const text = "DATABASE_URL=postgres://app:${PASSWORD}@db:5432/app?x=a=b\n\n";
    expect(derivedOf(text)).toEqual({ derived: [{ key: "DATABASE_URL", template: "postgres://app:${PASSWORD}@db:5432/app?x=a=b" }] });
    expect(derivedText(derivedOf(text).derived)).toBe(text.trim());
    expect(derivedOf("URL=no references").bad).toBe(0);
    expect(derivedOf("=${A}").bad).toBe(0);
  });
});
